### ISSUE TITLE
Question: PostGraphile to flatbuffers

### ISSUE THREAD

**Issue by shaunc** [graphile/postgraphile#1011]
I'm submitting a ... 

* [X] question 

PostGraphile version:

Current

--- 

I am designing a data visualization tool on top of an existing postgress database. Postgraphile is very tempting. I worry that a subset of queries will have a lot of data. (10s of MB in json, though should compress well). I was also considering using flatbuffers as a wire protocol. (flatbuffers in particular so I can use without unpacking on the client.)

Would it make sense to create a GraphQL -> flatbuffers translator in front of PostGraphile?  (Can PostGraphile stream data, or does it need it all in memory to transform it?) Should I rather plan on just creating an alternate path for the interfaces I need to optimize?

**Comment by benjie** [comment]
PostGraphile uses the reference GraphQL implementation which resolves the query up front, so there’s no streaming. You can however take the results direct from the GraphQL schema (i.e. in JS native JSON format) and deal with that how you wish rather than serialising them and sending over HTTP. Start here:

https://www.graphile.org/postgraphile/usage-schema/

And then benchmark to see if PostGraphile can do what you need. Feel free to come chat with us on Discord about it: http://discord.gg/graphile

**Comment by shaunc** [comment]
Thanks! My tentative plan is to start with PostGraphile for everything in the prototype, then split off the specific queries I need to be optimized into a separate service. I'll leave a note here if there seems to be another path or I have interesting benchmarking info; no need to keep this issue open, though.
