### ISSUE TITLE
Whitelisting via Smart Comments

### ISSUE THREAD

**Issue by madflow** [graphile/postgraphile#1018]
I'm submitting a ... 

* [ ] bug report
* [x ] feature request
* [ ] question 

As I started to implement Postgraphile for our product, I began with adding `@omit` to every table, view and function. Then I removed the `@omit` for the tables I want to expose at the moment.

For me - this is also a security feature and in security whitelisting is better than blacklisting, because of the unknown function that everyone forgets to blacklist.

So the feature request is: 

* Add a `whitelisting` mode to the options (one more option :S )
* Add the ability to `@include` tables etc, and operations like `@omit` does.
* `@omit` would beat `@include` when in doubt

**Comment by benjie** [comment]
Hi @madflow. I totally agree that whitelisting is better than blacklisting for security. I thought about this long and hard when I first introduced the feature, but ultimately concluded that the `@omit` smart comment is not intended for security (instead use `--no-ignore-rbac` combined with database permissions), and I needed to allow it to evolve. This means from time to time I may add a new field to omit, for example I might start splitting forward vs backward connections on relations soon. If we had whitelisting too then I would not be able to make this addition without it being a breaking change since the `@include`s would no longer include it and things would be removed unexpectedly from users schemas when they upgrade. At some point in the future `@omit` may be sufficiently stable that a whitelist is possible, but for now it is not.

You might be interested in this "omit by default" plugin from our docs - it automatically adds `@omit` to all tables and then you can override on a per-table basis. The same could be done for functions, attributes, relations, etc.

https://www.graphile.org/postgraphile/plugin-gallery/#Customisation__OmitMutationsByDefaultPlugin
