### ISSUE TITLE
Feature Request: expose health check endpoint

### ISSUE THREAD

**Issue by marshall007** [graphile/postgraphile#1098]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version: v4.4.0

For deployments within containerized environments, it would be convenient if the server exposed a default health check endpoint (conventionally `/healthz` in Kubernetes). A simple `200`/`500` status code with an empty response would be enough, but it might make sense to expose some basic metadata as well. At minimum, I think this endpoint should check for:

- schema build errors (`200` if recoverable)
- connection to postgres
- successful startup of `postgraphile`

Some examples:

```js
// status: 200
{
  "schema": true,
  "postgraphile": true,
  "database": true
}
```

```js
// recoverable schema errors
// status: 200
{
  "schema": false,
  "postgraphile": true,
  "database": true
}
```

```js
// fail to connect to postgres
// status: 500
{
  "schema": false,
  "postgraphile": true,
  "database": false
}
```

**Comment by benjie** [comment]
This sounds like it should be a server plugin (namely because I don’t think it should be added by default because it risks overriding any healthz endpoint the user has added themselves). Since we don’t keep connections open to the database for more than a few idle seconds (8?), would you want this to make its own connection to DB, or to check the initial connection succeeded, or perhaps something more complex like seeing if the last connection attempt succeeded/failed?

**Comment by marshall007** [comment]
I was thinking it should probably make it's own connection to the db to check for connectivity at the time the health check is being performed. The `postgraphile` check in the above examples would necessarily imply the initial connection succeeded.

**Comment by benjie** [comment]
I think this can entirely be achieved via a server plugin:

- use `postgraphile:options` to tweak `appendPlugins` to add a schema plugin using `makeProcessSchemaPlugin` that toggles a variable to say that the schema has been generated (this is the `"schema": true`)
- use `postgraphile:http:handler` to intercept the result if it's for us (if it is, return `null`, otherwise return the incoming request)https://github.com/graphile/postgraphile/blob/d2374174adfb363c20fc068aea255ad45bbbe708/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L435-L446

Not sure what the difference between postgraphile: true and schema: true is.

**Comment by benjie** [comment]
Closing this as I don't think any action is necessary

**Comment by jackbravo** [comment]
I'm guessing this is because someone wanted to run the server on a kubernetes or similar environment, where a health check will help know if each instance of the service is running correctly.

I would like to know how one would do something similar but for the worker instead of the server. But I guess this is a question for https://github.com/graphile/worker

**Comment by AndresJulia** [comment]
So what is the health check path? @benjie

**Comment by benjie** [comment]
Whatever path you use in the server plugin you write 😉

**Comment by joelmukuthu** [comment]
Hi @benjie, thanks for your guidance on this here! Is there a way to probe postgraphile's status from outside postgraphile? For instance, if one already has a `/healthz` endpoint (that is not a postgraphile plugin) that checks various things and would like to include the graphql-server status in there. Is this possible?

**Comment by benjie** [comment]
@joelmukuthu If you use library mode then when you build your middleware store it somewhere:

```js
const middleware = postgraphile(...);

app.use(middleware);
```

The middleware has some helper methods on it, you probably want the `getGraphQLSchema` method. You could do something like:

```js
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
/**
 * Returns a promise that resolves to true if the schema's good, false if not (or if we can't figure it out within a second.
 * /
const healthCheck = () => {
  return Promise.race([
    sleep(1000).then(() => false),
    middleware.getGraphQLSchema().then(() => true).catch(() => false)
  ]);
}
```

**Comment by joelmukuthu** [comment]
Perfect, thank you @benjie!

**Comment by villelahdenvuo** [comment]
Does anyone have an example or know a 3rd party plugin for a health check route?

**Comment by villelahdenvuo** [comment]
@ermineaweb Thanks for the tip! That looks helpful, however it would be nice to also check if postgraphile has a working DB connection and schema.

So far our setup has been very stable so we haven't had a strong need for this, but if we encounter instability we will invest more time in figuring out a solution.
