### ISSUE TITLE
Docker: sprinkle in some plugins

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#1107]
Would be nice to include some plugins that people commonly want so they don't have to build a new image just to install them:

- @graphile/subscriptions-lds
- @graphile/pg-pubsub
- @graphile-contrib/pg-simplify-inflector
- postgraphile-plugin-connection-filter
- @graphile-contrib/pg-order-by-related
- @graphile-contrib/pg-many-to-many

Other suggestions welcome.

(They won't be enabled by default, but people can opt into them on the CLI as usual.)

**Comment by mathroc** [comment]
I'd like to add @graphile-contrib/pg-order-by-related too

**Comment by marton78** [comment]
@graphile-contrib/pg-many-to-many please!

**Comment by benjie** [comment]
I think we can just add:

```docker
RUN yarn add @graphile/subscriptions-lds@4.x @graphile/pg-pubsub@4.x @graphile-contrib/pg-simplify-inflector@4.x postgraphile-plugin-connection-filter@1.x @graphile-contrib/pg-order-by-related @graphile-contrib/pg-many-to-many
```

to the very bottom of the Dockerfile:

https://github.com/graphile/postgraphile/blob/c46934947b8a91a35efe677d16bb0a9b78805ef2/Dockerfile#L52

If someone wants to give this a go and test the various plugins work as expected I'd appreciate it. I've added version numbers for the ~stable ones.

I'm not sure what this means for supporting this docker file; I wonder if there should be a vanilla PostGraphile image, and then a separate one with all the bells and whistles? I'm also concerned about breaking changes in the various plugins. Opinions from people more knowledgeable about Docker than myself very welcome. (I'm not very knowledgeable.)

**Comment by archlemon** [comment]
You could potentially use [ARG](https://docs.docker.com/engine/reference/builder/#arg) to add optional features in the build process, via `--build-arg ARG_NAME=true`.
Then you could use `if [$ARG_NAME = "true"]...` to run the extra commands.

There are a couple of options I can see being useful
- Being able to set specific versions for each plugin
- Choosing which plugins to install, without specifying versions
- Choosing to just install all plugins as above

**Comment by benjie** [comment]
@archlemon Thanks for sharing; I wasn't previously aware of this. So since it's at build time, maybe we need two versions: one that's small that you can customise as you need, and one that's got a load of plugins in it by default (kitchen-sink style)?

**Comment by ardeaf** [comment]
While waiting for this issue to get solved, what's the best practice for using the docker image? I'm considering just pulling the dockerfile from this repo and appending the plugins I want as you [said here](https://github.com/graphile/postgraphile/issues/1107#issuecomment-507761637)

**Comment by mathroc** [comment]
@ardeaf you can use the published docker image instead of pulling the Dockerfile from here:

```Dockerfile
FROM graphile/postgraphile:v4.4.5
RUN yarn add @graphile/subscriptions-lds @graphile/pg-pubsub @graphile-contrib/pg-simplify-inflector postgraphile-plugin-connection-filter @graphile-contrib/pg-order-by-related @graphile-contrib/pg-many-to-many
```

@benjie it's probably very hard to include most nice to have plugins, I think including only `@graphile-contrib/pg-simplify-inflector` in the image should be enough. if you add more you'll have to deal with version upgrade of the plugins, conflicts, etc. it gonna take you a lot of time to maintain

instead what you might want to add a helper that install and enable plugins, eg: `docker-postgraphile-plugin-install @graphile/subscriptions-lds @graphile/pg-pubsub`

`docker-postgraphile-plugin-enable` would install them with yarn and configure the image to automatically enable the plugin (the php image has similar helpers for php extensions)

with [ONBUILD](https://github.com/graphile/postgraphile/issues/1107) it would allow to make it very simple to build a new image with additional plugins

if you have this in the Dockerfile :

```Dockerfile
ARG PLUGINS=""
ONBUILD RUN docker-postgraphile-plugin-enable $PLUGINS
```

you could build a new image with `docker build --arg PLUGINS="postgraphile-plugin-connection-filter @graphile-contrib/pg-order-by-related @graphile-contrib/pg-many-to-many graphile/postgraphile -t my/postgraphile"`

**Comment by benjie** [comment]
Interesting idea. And you're right about maintenance, that's one of the reasons I've not done it already.

Regarding automatically enabling, I'm thinking best bet might be to do that via the `postgraphilerc` file, like we already do for the `host` setting.

**Comment by benjie** [comment]
I'm closing this because I don't want to maintain it :wink:
