### ISSUE TITLE
[Bug] Double precision being returned as Int

### ISSUE THREAD

**Issue by lucasavila00** [graphile/postgraphile#1109]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

v.4.4.1 (latest)

Minimal SQL file that can be loaded into a clean database:

```sql
CREATE TABLE location (
    id serial PRIMARY KEY,
    lat double precision,
    lng double precision,
);

insert into location (lat, lng) values (-42.0, -21.0);
```

Steps to reproduce:
Get this value somehow. (graphiql for instance)

Current behavior:
It will return json like this:

```json
"lat": -42
```

Expected behavior:
Return json like this:
```json
"lat": -42.0
```

Why fix it:
When using the data on Dart the parser heuristic to determine if it is a Int of Float will get confused and will parse it as Int. Then the application crashes because of invalid type.
If you're using JS that doesn't distinguish between int and float then this won't be apparent but in other languages this creates a hidden, hard to diagnose bug.

**Comment by benjie** [comment]
Thank you for filing this issue, but I'm sorry to say that I will not be fixing this. The GraphQL schema correctly states that the entry is a `Float`, and returning the number `-42` as that float is perfectly correct, and well within both the JSON and the GraphQL specs. Forcing all users to suffer the performance hit of PostGraphile manually constructing the resulting JSON string rather than using JavaScript's built in (and fast) `JSON.stringify` would be an unacceptable cost.

I suggest that you use something like `graphql-code-generator` to generate the type signatures for your types rather than relying on heuristics. This will also help you differentiate between String and other string-like types such as ID, DateTime, Cursor, etc.

**Comment by benjie** [comment]
Having said that; you could potentially accomplish this by adding a [server plugin](https://www.graphile.org/postgraphile/plugins/) interface around this line of code:

https://github.com/graphile/postgraphile/blob/d2374174adfb363c20fc068aea255ad45bbbe708/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L858

If you wanted to do so, I'd be happy to give you guidance on how to write the PR.

**Comment by lucasavila00** [comment]
I'm already using a types generator that makes sure all floats are floats, I just reported it because I though someone else may get troubles with it.
I thought this library was not following the spec but I didn't take the time to read it, I'm sorry :/
Thanks for the attention 👍
