### ISSUE TITLE
Network fetch error apollo client postgraphile

### ISSUE THREAD

**Issue by CarlFMateus** [graphile/postgraphile#1113]
Good morning I do not speak English well.
I have two projects that are being implemented with apollo client and postgraphile the problem is that there is an intermittence in the services. I am presented with this error:
Error: Network error: Failed to fetch
at new ApolloError (bundle.esm.js:76)
at bundle.esm.js:1556
at bundle.esm.js:1977
at Set.forEach ()
at bundle.esm.js:1975
at Map.forEach ()
at QueryManager.broadcastQueries (bundle.esm.js:1973)
at bundle.esm.js:1451

We don't have any related errors in the API. It seems to be when the user leaves the app open for a while; does Apollo have any bugs related to this when the user leaves an app open for a while?
Please help me with this problem I have two projects and I can not find a solution. Thanks

**Comment by chadfurman** [comment]
Seems like a question for apollo devs. Sounds like the user is dropping connections, perhaps on a 3g/4g connection? Those tend to timeout and then reconnect often.

Regardless, ask in the apollo GitHub for apollo related service.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by benjie** [comment]
I'm not aware of any issues in Apollo or PostGraphile that would cause this. I'm afraid I don't know where to start debugging this without hands on the machine.

I'm going to close this because I don't believe it's a bug in PostGraphile, but feel free to keep discussing it below. You can also ask for help on our chat: http://discord.gg/graphile.

**Comment by CarlFMateus** [comment]
Benjie you do not have an example of connection between apollo client and postgraphile through express is that as you know I have two projects implementing these technologies. I would really appreciate it

**Comment by benjie** [comment]
All my production PostGraphile projects use Apollo Client and Express; I've never had the issue you mention.

Here's a couple demo projects:

- https://github.com/graphile/bootstrap-react-apollo (uses Express)
- https://github.com/graphile/examples (uses Koa rather than Express)

Our docs also show how to use PostGraphile with express:

https://www.graphile.org/postgraphile/usage-library/
