### ISSUE TITLE
 error generating relationship between tables

### ISSUE THREAD

**Issue by CarlFMateus** [graphile/postgraphile#1149]
Good afternoon, this is my problem. I have a table called talents within this table, there are two columns that relate to the city table, but it generates this error.
![Captura de pantalla de 2019-08-30 15-29-19](https://user-images.githubusercontent.com/46789400/64049817-b57eb600-cb3b-11e9-9f17-faf409c5b806.png)
I already made the respective intelligent comments to the foreign keys but the error still appears.
The relationship between the tables are these
![error](https://user-images.githubusercontent.com/46789400/64051746-dba75480-cb41-11e9-9fe5-7dc45ebffcb8.jpeg)
What solution can you give me to this problem thanks

**Comment by mattbretl** [comment]
@benjie Are you able to move this to the pg-many-to-many repo?

@CarlFMateus There are two many-to-many relationships between `city` and `plan` (one uses  `birth_city_id` and the other `residence_city_id`) which leads to two fields (`plansByTalentBirthCityIdAndPlanId` and `plansByTalentResidenceCityIdAndPlanId`) being generated on your `City` type.

Since the error message lists the conflicting field name as `plans`, I'm guessing you're using the custom inflector plugin example from the pg-many-to-many documentation. There was a warning in the docs that previously offered two suggestions for handling field name conflicts: customize the inflector function, or use smart comments. Unfortunately, smart comments can't actually fix this.. there are more fields being generated (2 in each direction = 4 total) than constraints we can add smart comments to (3). You can specify two unique field names using two of the constraints, but whichever field name you specify using the third constraint will be used for two fields on one type, causing a conflict.

I just updated the docs by removing the suggestion to use smart comments to fix conflicts, and also made the warning message more prominent.

**Comment by benjie** [comment]
(Apparently I can’t move it there; maybe because different org?)

**Comment by CarlFMateus** [comment]
I use the complement of pg many to many. The problem is that I don't know if the relationships are well done. The talent table needs a field of city of residence and another field of city of birth. I don't know if relations are good, how can I solve this?

**Comment by mattbretl** [comment]
We can continue the discussion in https://github.com/graphile-contrib/pg-many-to-many/issues/21

@benjie, feel free to close this.
