### ISSUE TITLE
input ENUM can be string with ""

### ISSUE THREAD

**Issue by roytan883** [graphile/postgraphile#1201]
I'm submitting a ... 

* [ *] bug report

PostGraphile version:

4.5.0

Steps to reproduce:

```
mutation {
  updateShareMediaV2DescByDescBaseId(input:{
    descBaseId:"1574935785950_746686e4252f",
    shareMediaV2DescPatch:{
      contentType: "TEXT",
      content:"hi"
    }
  }){
    base{
      desc{
        descBaseId contentType content
      }
    }
  }
}
```

Current behavior:
```
{
  "errors": [
    {
      "message": "Expected type EnumDescContentType, found \"TEXT\". Did you mean the enum value TEXT?",
      "locations": [
        {
          "line": 5,
          "column": 20
        }
      ],
      "stack": [
        "GraphQLError: Expected type EnumDescContentType, found \"TEXT\". Did you mean the enum value TEXT?",
        "    at isValidScalar (/home/aaa/server/node_modules/graphql/validation/rules/ValuesOfCorrectType.js:147:25)",
```

Expected behavior:
```
{
  "data": {
    "updateShareMediaV2DescByDescBaseId": {
      "base": {
        "desc": {
          "descBaseId": "1574935785950_746686e4252f",
          "contentType": "TEXT",
          "content": "hi"
        }
      }
    }
  }
}
```

Currently, the `contentType` enum MUST be TEXT without ", then it works. This works:
```
mutation {
  updateShareMediaV2DescByDescBaseId(input:{
    descBaseId:"1574935785950_746686e4252f",
    shareMediaV2DescPatch:{
      contentType: TEXT,
      content:"hi"
    }
  }){
    base{
      desc{
        descBaseId contentType content
      }
    }
  }
}
```

The strange thing is that the retrun value of  `contentType` is "TEXT", but why input can not be "TEXT" ?

**Comment by benjie** [comment]
This error is coming from graphql-js, the reference implementation of GraphQL. It is not a bug. Here’s the relevant part of the GraphQL spec: https://graphql.github.io/graphql-spec/June2018/#sec-Enum-Value

The reason the result has quotes is because the result is JSON which doesn’t support unquoted literals.

If you were to pass variables into your query where the variables were JSON (this is how you should be passing dynamic values into your GraphQL operations) then you can use quotes because it’s JSON and it gets coerced into GraphQL before the operation is executed.

**Comment by roytan883** [comment]
@benjie yes, later i found using variables can has quotes, it works , i just forget to close this issue. thanks for explain it.

**Comment by benjie** [comment]
No problem :)
