### ISSUE TITLE
Schema-only usage does not support debugging

### ISSUE THREAD

**Issue by ab-pm** [graphile/postgraphile#1202]
I just noticed that `debugPgClient` is called only on `postgraphile(…)` "library usage", but not with `createPostGraphileSchema`/`withPostgraphileContext`. Would it be possible (or make sense) to install the same "enhancer" on its pool?

If this cannot properly be fixed, please a) export `debugPgClient` so that one can install it on own pools and b) document it on the *Debugging* page.

**Comment by benjie** [comment]
The GraphQL schema doesn't contain PostgreSQL client acquisition code, so it doesn't make sense to add it to `createPostGraphileSchema`.

`withPostgraphileContext` should be handed a pre-constructed `pgPool`. Augmenting this pool would have to be well documented, we really oughtn't fiddle with it. (We oughtn't fiddle with the `pgPool` passed to `postgraphile` either, but that ship sailed a long time ago. I'd consider doing it for consistency, but worry that it'd be a breaking change since our modifications are not 100% backwards compatible.)

Exporting the `debugPgClient` method would make the most sense, IMO.

I challenge the "does not support debugging" - `DEBUG=graphile-build-pg:sql` should enable debugging of at least the SQL statements that are executed by the schema directly. When you're doing schema-only usage you're really taking things into your own hands, so I think managing your own debugging makes sense.

**Comment by ab-pm** [comment]
> we really oughtn't fiddle with it.

Agreed.

> Exporting the `debugPgClient` method would make the most sense

:+1:

> `DEBUG=graphile-build-pg:sql` should enable debugging of at least the SQL statements that are executed by the schema directly.

Ah, thanks, I guess I had not seen that - but the problem is that it doesn't debug the SQL statements issued by `selectGraphQLResultFromTable` in an extend-schema plugin.

**Comment by benjie** [comment]
Oh really? That needs fixing.

**Comment by benjie** [comment]
https://github.com/graphile/graphile-engine/pull/668 makes selectGraphQLResultFromTable debug via `DEBUG=graphile-build-pg:sql`
