### ISSUE TITLE
`externalUrlBase` behaves incorrectly with proxies + subscriptions + graphiql

### ISSUE THREAD

**Issue by cmanou** [graphile/postgraphile#1232]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.4.4 (but applicable to all versions since #1070)

Steps to reproduce:
1. Have a running instance of postgraphile with `graphiql` enabled (eg: http://localhost:3000/graphql)
2. Have a proxy server in front of the postgraphile server that routes on a path (eg: https://example.com/api/graphql -> http://localhost:3000/graphql)
3. Alternate setting `externalUrlBase` to `/api` or undefined

Current behavior:
- If `externalUrlBase = /api` graphiql will render, and be able to execute `mutation + queries`. Though any subscriptions requests will fail to complete the upgrade handshake due to the path not matching at https://github.com/DvdGiessen/postgraphile/blob/44c44e2196883b7d659ff796e1eac8c4557e0884/src/postgraphile/http/subscriptions.ts#L157 

- If `externalUrlBase = ''` graphiql will render but will be unable to retrieve the schema or execute any requests. Subscriptions will connect correctly as expected via external clients. 
https://github.com/graphile/postgraphile/blob/master/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L401

Expected behavior:
That it works in both cases, this will most likely mean that there will have to be 2 config options as opposed to just `externalUrlBase`. One option to support the mounting of postgraphile at an express route (ie the reasoning behind the change that was made in #1070 ) and the other which is purely for graphiql config

**Comment by benjie** [comment]
Yes, you're right - we need two settings here. If we take a slightly more complex example:

https://example.com/api/graphql -> http://localhost:3000/route/graphql

assuming you have something like `app.use('/route', postgraphile(...))`

To PostGraphile within Express over HTTP we have `graphqlRoute = '/graphql'` and we can detect `originalUrl = '/route/graphql'` so we can infer our "internalUrlBase" to be `/route` but we know nothing about our "actual" location which is `/api/graphql`. Setting `externalUrlBase` to `/api` here should work as expected since we match on `req.url` and `graphqlRoute` directly so we don't care about `originalUrl`.

To PostGraphile websockets we need to match `/route/graphql` requests directly since we have no express middleware to do the `originalUrl` dance for us, and we know nothing of the external API. So we need an `internalUrlBase = '/route'`.

Often `externalUrlBase` and `internalUrlBase` are the same, which is how we've got away with having just one setting so far, but apparently no more!

I'd love a PR for this :+1:

**Comment by danbiagini** [comment]
Alright, I'll bite.  Just hit this, and seems like a reasonably straight forward place to jump in as 1st time contributor?

**Comment by benjie** [comment]
I think so! :raised_hands: Any questions; @ me on #dev-postgraphile in Discord: https://discord.gg/graphile

**Comment by benjie** [comment]
Hey @danbiagini did you get a chance to look at this?
