### ISSUE TITLE
pagination limit maximum "first" and "last"

### ISSUE THREAD

**Issue by roytan883** [graphile/postgraphile#1258]
I'm submitting a ... 

* [x] feature request

PostGraphile version: Library: 4.6.0

* Current behavior:
GQL query as plain text or with variables, `first` can be very large, like 99999

* Expected behavior:
somewhere can config the maximum pagination, `first:` and `last:`

so far, i can do it by modify src, but i think it should controlled by config options for easy usage. And modify src will be replace by `yarn install` or `npm install` when add new lib.

> node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgFirstLastBeforeAfter.js

```
if (typeof first == 'number' && first > 100) {
    queryBuilder.first(100);
}
else {
    queryBuilder.first(first);
}
```

**Comment by benjie** [comment]
In `@graphile/pro` we achieve this via an additional GraphQL validation rule so the query can be rejected before even reaching the resolvers.

**Comment by benjie** [comment]
This cannot be reprensented via GraphQL default argument values because a default value for `first:` wouldn't make sense if you were paginating backwards with `last:`. So I definitely wouldn't add it this way.

Adding a limit silently without informing the client is a faux-pas and goes against the best practices of GraphQL: how would the client even know they weren't getting all the data they requested? How would they know the pagination limit that was used? So I definitely wouldn't add it this way either.

With the above two points in mind, it's on the client to ensure they add limits to the request; and it's on the server to validate that the requested limits are within range. This can be achieved:

- with a custom GraphQL validation rule which you can install using the [Server Plugins](https://www.graphile.org/postgraphile/plugins/#writing-your-own-plugins) interface, as the pro plugin does
- via persisted operations with hard coded fetch limits in your operation documents; you can achieve that with a plugin such as this one: https://github.com/graphile/persisted-operations
