### ISSUE TITLE
makeWrapResolversPlugin: Typescript argument types not exported.

### ISSUE THREAD

**Issue by cellis** [graphile/postgraphile#1279]
I'm submitting a

* [x] feature request

PostGraphile version: ^4.4.4

I'm trying to use the makeWrapResolversPlugin,
```ts
const registerCustomerWithCheckout:Plugin = makeWrapResolversPlugin({
  Mutation: {
    
  }
})
```

I noticed that `Mutation` doesn't show up in the intellisense, even though the arguments for `makeWrapResolversPlugin` are typed. I know we can probably pull them out with Typescript's `Arguments`, but it seems much cleaner to just export the types: `ResolverWrapperRules | ResolverWrapperRulesGenerator`. 

Is there something I'm missing?

**Comment by benjie** [comment]
TypeScript doesn't currently know what types are defined in your schema; remember that in V4 graphile-engine is implemented in Flow rather than TypeScript. In version 5 we're moving to TypeScript throughout, but I'm not entirely sure if it will be able to add runtype type augmentations so we can determine which types are defined because I'm not sufficiently wizard at TypeScript to know how to do that.

**Comment by cellis** [comment]
@benjie thanks! Yeah, bummer for it being in Flow, can't believe I used it for so long.
