### ISSUE TITLE
pg and @types/pg update needed

### ISSUE THREAD

**Issue by warent** [graphile/postgraphile#1313]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

4.7.0

Current behavior:
The documentation states: 

> An object or string that will be passed to the [pg][] library and used to connect to a PostgreSQL backend. If you already have a client or pool instance, when using this function you may also pass a pg client or a pg-pool instance directly instead of a config.
https://www.graphile.org/postgraphile/usage-schema/

But the first parameter is typed to only accept a PgConfig
`export declare const createPostGraphileSchema: (pgConfig: PgConfig, schemas: string | string[], options?: PostGraphileCoreOptions) => Promise<GraphQLSchema>;`

Expected behavior:
Type should be a union to support pg client and pg pool as noted in docs. e.g.
`export declare const createPostGraphileSchema: (pgConfig: PgConfig | Pool | PoolClient, schemas: string | string[], options?: PostGraphileCoreOptions) => Promise<GraphQLSchema>;`

**Comment by warent** [comment]
Currently working around this by doing something like: createPostGraphileSchema(pool as any,

**Comment by warent** [comment]
Actually this appears to be related to the latest minor versions of `@types/pg `and `pg` having breaking changes. The fix is to downgrade those until postgrahile is updated

**Comment by benjie** [comment]
I really don't follow what this issue is.

This line <https://github.com/graphile/graphile-engine/blob/v4.7.0/packages/postgraphile-core/src/index.ts#L113> defines `PgConfig`:

```
type PgConfig = Pool | PoolClient | string;
```

And `@types/pg` and `pg` both have ranges that cover the latest versions of these packages that are available (punch then into https://semver.npmjs.com/ to check for yourself)

https://github.com/graphile/postgraphile/blob/637d5ca5258c11f15de00a9a5b9c1f033b1e99b1/package.json#L68

https://github.com/graphile/postgraphile/blob/637d5ca5258c11f15de00a9a5b9c1f033b1e99b1/package.json#L54

So I'm not really sure what issue you're facing or how to solve it for you.

Since I can't update these versions (they already cover the latest available versions) I'm going to close this issue, but once you have more detail about what's going wrong please feel free to open a new issue :+1:

**Comment by farcasmihai91** [comment]
This is happening for me as well, in the `schema-export.ts` file (graphile starter):

```
scripts/schema-export.ts(14,7): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'PgConfig'.
  Type 'undefined' is not assignable to type 'PgConfig'
```

```
const schema = await createPostGraphileSchema(
      process.env.DATABASE_URL,
      process.env.SCHEMA_NAME,
      getPostGraphileOptions({ rootPgPool })
);
```

```
"@types/pg": "7.14.5",
"pg": "^8.3.3",
"postgraphile": "^4.9.0",
"ts-node": "^9.0.0"
```

**Comment by benjie** [comment]
Have you changed any versions in the starter? Are you using `yarn`?

For me, this works fine:

```
~/Dev/graphile/starter$ yarn server schema:export
yarn run v1.22.5
$ yarn workspace @app/server schema:export
$ node -r @app/config/env node_modules/.bin/ts-node -O '{"rootDir":null}' scripts/schema-export.ts
GraphQL schema exported
Done in 2.93s.
```

**Comment by farcasmihai91** [comment]
Well, I'm not using `yarn`, that's true.
I found the issue however, and it was because `process.env.DATABASE_URL` was of type `string | undefined` and TS did not like the undefined part...

However I realized I mistakenly removed the the non-null assertion operator (`!`) after the env variable -> `process.env.DATABASE_URL!`. It's working now after adding the `!` back.

@warent make sure it's not the case for you as well.

@benjie thanks for double checking and sorry for the confusion...
