### ISSUE TITLE
What do you think about hasura live queries (scaling 1 million users) ?

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [graphile/postgraphile#1336]
* [x] feature request

Have you thought to use their approach and borrow some of the optimizations from them?
Here is the article: https://github.com/hasura/graphql-engine/blob/master/architecture/live-queries.md

They combine all active queries into one sql And then the results are returned to users by id. Hasura not use RLS. 
Hasura use app level roles and privileges, and he CAN make access check in sql query. And therefore it can unite the queries of different users into one big SQL query.

Is it possible to combine all queries in the same way while preserving PostgreSQL RLS in postgraphile? Is it possible to locally set different roles in PARTS of one big SELECT?

```sql
SELECT 
(SET ROLE = admin,  SELECT * FROM ...) as user_id_1 // id of the user the request belongs to
(SET ROLE = anoninmous,  SELECT * FROM ...) as user_id_anonymous // id of the user the request belongs to
```
then:
```javascript
const result =  await db.liveQueryCheck()

// And we distribute the results to users, To each his part
user1.sendsendLiveData(result["user_id_1"])
userAnonymous.sendLiveData(result["user_id_anonymous"])
```

etc. Well, you get the concept, the problem is how to use different RLS in different parts of the same request?

Moreover, usually in 90% of cases, users have the same query set by the developer during the site layout. They only change the user_id and role data, which means that you can wrap such queries in a function, generate dynamically functions, call them with different arguments, etc.

Like this:
```sql
create function get_query_data(id bigint, role String) $$
  set local ROLE = role;

  SELECT * FROM ...
$$
```

end then:

```sql
SELECT 
get_query_data(1, "admin") as user_id_1 // id of the user the request belongs to
get_query_data(0, "anonymous") as user_id_anonymous // id of the user the request belongs to
```

well something like that

**Comment by MaxmaxmaximusAWS** [comment]
Oh, I came up with. There are usually not many roles, and you can create a separate large SQL SELECT for each role =) then you don't have to use functions. =)

**Comment by benjie** [comment]
This won’t work for most PostGraphile users since they use per-user claims such as user_id and not just roles. Thus batching the requests like that wouldn’t work.

**Comment by MaxmaxmaximusAWS** [comment]
@benjie What you have just said suggests that you did not read the article from the link that I gave. Did you read?

**Comment by MaxmaxmaximusAWS** [comment]
Now the algorithm is like this:

1) the first graphql request comes
2) you immediately compile it into SQL and start executing
3) While it is running, new graphql requests come, you put them in the queue
4) as the first query finishes executing, you get and combine all graphql queries from the queue into one big SQL query, and execute it
5) While it is running, the queue is filled with new graphql requests

**Comment by benjie** [comment]
I have read the article before and am familiar with how Hasura's live queries work. If we have 10,000 users connected, they have 10,000 `user_id`s, which means we have to issue 10,000 SQL statements (or call 10,000 different versions of the function you propose). This doesn't allow us to leverage the same optimisations that Hasura are. Importantly this is because PostGraphile users typically don't just use a `role` claim, they *also* include things like `user_id` which RLS policies depend upon; e.g.

```sql
create policy select_own on notes for select using (user_id = current_setting('jwt.claims.user_id', true)::uuid);
```

In this case, PostGraphile does not know (or care) about this RLS policy, it just populates the SQL query like `select * from notes`, and PostgreSQL does the rest. This is a very simplified example, normally it would be much more complex policies often involving fetches to other tables which we have no way of emulating. So each unique set of claims needs its own queries/settings, which means we're still issuing 10,000 tasks to the database instead of 1 (whether those tasks be round-trips or function calls).

I appreciate your enthusiasm, but as I mentioned this will not work with PostGraphile-style RLS.

**Comment by MaxmaxmaximusAWS** [comment]
@benjie I will still try to come up with something, I'm sure there is a solution.

**Comment by benjie** [comment]
Hasura's live queries are faster, because their architecture doesn't allow for the level of customisability that PostGraphile offers and they've rolled a custom authentication solution rather than using PostgreSQL's built in RLS, so they've made different trade-offs.

**Comment by MaxmaxmaximusAWS** [comment]
@benjie  is it possible to somehow COUNT the given RLS, and compose a selector in SQL? After all, in fact, RLS is a set of SQL code, you can get it, and BUILD a large selector into our SQL.
