### ISSUE TITLE
Created Custom Function with Flaw, but Can't Debug it To See What Postgraphille is Passing to PostgreSQL

### ISSUE THREAD

**Issue by machineghost** [graphile/postgraphile#1339]
**I'm submitting a ...** 

* [X] bug report
* [ ] feature request
* [ ] question 

**PostGraphile version:**
4.7.0

**Minimal SQL file that can be loaded into a clean database:**

Not relevant (I used to have a bad custom function here, but I've since found the problem in my function, and it's not relevant to the issue ... though if the issue was fixed it would have helped me find my issue.)

**Steps to reproduce:**

Start by having a problem you need to debug with a custom function for Postgraphile ... and that problem *could be* input-related (eg. I included a `[]` in my function's `RETURNING` statement, which caused a confusing error about a malformed array literal ... and not understanding it, I *thought* the problem was with my function's inputs.)

**Current behavior:**

When you try to use your custom function, you'll get an error, and `handleError` will catch it ... but the `error` argument it gets passed (as I noted in a new comment on https://github.com/graphile/postgraphile/issues/929) is completely undocumented.  Critically, as far as I can tell at least, it doesn't include the parameters passed to the function.

This makes postgraphile a "black box" in some respect, because without seeing the inputs, you can't tell if Postgraphile is passing incorrect ones, or (as was the case with me) it's passing correct ones and your problem is elsewhere.

Even when I "explain" my GraphQL query to the function, I can only see the query being made ... there doesn't appear to be any way to log the parameters, just the query:

     "query": "with __local_0__ as (select __local_1__.* from \"public\".\"update_section_indices\"(array[row($1::\"pg_catalog\".\"int4\",$2::\"pg_catalog\".\"int4\")::\"public\".\"section_index_update\"]::\"public\".\"_section_index_update\") __local_1__) select ((case when __local_0__ is null then null else __local_0__ end))::text from __local_0__",

For debugging it would be helpful to see what Postgraphile is giving to Postgres (`$1` and `$2` in the above).

**Expected behavior:**

I can somehow (preferably both in GraphiQL and in `handleErrors`, but I'd settle for either) log the parameters that are being passed to Postgres.

P.S. I would be happy to submit a PR, either to improve documentation, or to add logging of parameters (or both) ... but I'm completely unfamiliar with the codebase and would need to be pointed in the right direction.

**Comment by benjie** [comment]
We very explicitly and very deliberately do not have a built in way of logging the values passed into an SQL query because this could be a big security and privacy issue if it is enabled on production by mistake. We've seen a lot of values like this being logged and only being discovered years later in other systems, and I'd very much like to avoid that happening in a PostGraphile system, even if it means developers have to put in a little more debugging effort if they think PostGraphile isn't doing the right thing.

We detail debugging techniques (including [how to open the Chrome Node inspect tool against PostGraphile](https://www.graphile.org/postgraphile/debugging/#advanced-getting-your-hands-dirty)) here:

https://www.graphile.org/postgraphile/debugging/

If you are using the Node debugger with `DEBUG="postgraphile:postgres"` envvar set (so that you can see the generated SQL), a breakpoint here will allow you to inspect the variables:

https://github.com/graphile/postgraphile/blob/8a0c6a8a68797f94f58eda48dc20f03405ebe000/src/postgraphile/withPostGraphileContext.ts#L519

(You could also mod that file in `node_modules` and add a `console.log` if you prefer.)

I'd happily accept a PR to the debugging page above (see the "Suggest improvements" link at the top of the page) that guided users how to do this in more depth, but I will not accept a PR that adds, for example, a flag that allowed logging these values. I _might_ consider adding a [server hook](https://www.graphile.org/postgraphile/plugins/) that allowed users to provide their own server plugins that would enable this though; that way they're explicitly opting in via said plugin (and hopefully the plugin would have a bold warning in the README about the potential pitfalls of using it in production).

**Comment by machineghost** [comment]
>We very explicitly and very deliberately do not have a built in way of logging the values passed into an SQL query because this could be a big security and privacy issue if it is enabled on production by mistake. 

I completely understand and sympathize with this concern, but at the same time I feel very strongly also that libraries shouldn't treat devs like children who don't know what they're doing.  Surely if there's a `dangerouslyLogValues: true` option no one is going to "accidentally" add it to their config?

**Comment by benjie** [comment]
You'd be surprised. People turn things on when debugging and forget to turn them off. People do `git commit -a` and don't bother to review the changes they've made. Further I don't think encouraging developers to use a debugger is treating them like children :wink:

**Comment by machineghost** [comment]
Fair enough; "better safe than sorry" :-)

**Comment by benjie** [comment]
I'm going to close this issue; but if you fancy raising a PR to the docs that'd be awesome :)
