### ISSUE TITLE
Evaluation of computed columns of nested (foreign) objects

### ISSUE THREAD

**Issue by Hyaxia** [graphile/postgraphile#1353]
#### Context:

Lets say we have two tables:

1. person table -> name, home_id (foreign key to home table)
2. home table -> id, address (computed column)

And the following data:

in person table with have the rows:

- 'name1', 1
- 'name2', 1
- 'name3', 2

in home table we have the rows:

- 1
- 2

We perform the next query:

```javascript
query MyQuery {
  person {
    nodes {
      home {
        nodes {
          address
        }
      }
    }
  }
}
```

#### Question:

How many times will the computed column for the home with id 1 will be called and why?

or, in other words,

In what stage the computed columns are evaluated and how?

**Comment by benjie** [comment]
Hi @Hyaxia; this is an incredibly complex question to answer because it depends on decisions that PostgreSQL's query planner makes. I suggest that you use our `EXPLAIN` feature (via `--enhance-graphiql`) to see the query plan and answer the question for yourself. If PostgreSQL is calling the function more times than it needs to, you can sometimes solve this by using the `COST` parameter on the function to increase the chances of PostgreSQL caching this stable function.
