### ISSUE TITLE
malformed record literal with table-based enums and functions

### ISSUE THREAD

**Issue by brendanmckenzie** [graphile/postgraphile#1365]
### Summary

I have a function that accepts a table record type as a parameter.  This type has a field that references a table-based enum.

When calling a function passing the table record type parameter with an enum value I am given the error message "malformed record literal"

In the example below, `new_thing()` fails, but `new_thing2()` works fine.

### Steps to reproduce

I created this simple test case for reproduction.

```sql
create table testenum ( enumval text primary key );
insert into testenum (enumval) values ('A');
comment on table testenum is '@enum';

create table things( id text primary key,
  enumval text not null references testenum (enumval)
);

create or replace function new_thing(f_input things) returns text
  language plpgsql
  volatile
as
$$
declare
  v_out text;
begin
  insert into things (id, enumval) values (f_input.id, f_input.enumval) returning id into v_out;
  return v_out;
end;
$$;

create or replace function new_thing2(f_id text, f_enumval text) returns text
  language plpgsql
  volatile
as
$$
declare
  v_out text;
begin
  insert into things (id, enumval) values (f_id, f_enumval) returning id into v_out;
  return v_out;
end;
$$;
```

### Expected results

Expected to see the function called successfully without the error message.

### Actual results

malformed record literal is thrown when passing an enum value.

### Additional context

- Postgraphile 4.9.0
- PostgreSQL 12.4

### Possible Solution

Work around is to pass the parameter as text rather than enum.

**Comment by benjie** [comment]
This is because we gave the fake enums a type name that matches the table name; so it's taking `'A'::testenum`, which we thought was our enum but PostgreSQL thinks is a table type (because it is!).

I've solved this by checking if a type is fake, and if so using `::unknown` instead; so now it's `'A'::unknown` which gets cast automatically based on usage. I'm sure there are circumstances under which this won't work, but I'm not sure how best to solve that.
