### ISSUE TITLE
Cannot create custom mutations that share the name of the "would be" mutation

### ISSUE THREAD

**Issue by Tycholiz** [graphile/postgraphile#1372]
## Summary
I use a many:many relation in my application, so I have a composite table. I've opted to forgo the `id` row on this table, in favour of simply using a combination of both of the ids that the table references.

I understand that Postgraphile will not generate a mutation for us if the table does not have an id, so instead of adding an id, I've opted to just create my own pg function. Interestingly, I cannot name the table `delete_item`, since this is the naming convention adopted by Postgraphile. To work around this, I simply had to name it something else.

This issue doesn't particularly bother me, but I don't know if it known or not, and would be something easy to fix. By any means, doing my good citizenry by reporting it. Up to you to decide what to do with this,

**Comment by benjie** [comment]
Hey @Tycholiz; naming conflicts only occur when something else is created with that same name. To prevent a CRUD operation being created so that you can replace it with a custom mutation (without renaming), you should use the `@omit delete` smart tag on the relevant table to prevent the delete mutation being created in the first place :+1:

**Comment by Tycholiz** [comment]
Ah gotcha, apologies for not digging further into that. All good now
