### ISSUE TITLE
Change query params inside hook before request

### ISSUE THREAD

**Issue by Hyaxia** [graphile/postgraphile#1402]
### Summary

I was wondering if there is an option to change/inject new parameters to the query.
And if there is, is it also possible to change the request parameters entirly? (delete parameters, change them, etc...)
Could not find anything about it in the docs, maybe I missed it.

Thanks in advance!

### Additional context

I have a route to create a user.
But the thing is I have firebase as the source of truth for the users in the system,
and I want to take the uid that I receive from firebase and inject it into the request that creates the new user,
so they will both use the same uid.
The work around is to send two requests, first to firebase, get the uid, then to user service,
but I think it will probably be much cleaner if I just perform the request by myself and inject it into the query.

**Comment by benjie** [comment]
There's a number of options here depending on exactly what you want; but I'd probably recommend using `pgSettings` to indicate the uid via a PostgreSQL setting, and then using a column default in PostgreSQL that reads this value.

If I've missed the mark, it's also worth researching:

- `makeWrapResolversPlugin` + `additionalGraphQLContextFromRequest` - wrap the existing resolver, and rewrite the arguments passed
- `makeExtendSchemaPlugin` - write your own mutation rather than re-using an existing one
- A server plugin, specifically the `postgraphile:httpParamsList` hook
