### ISSUE TITLE
Connecting to a prod database

### ISSUE THREAD

**Issue by oshalom-dcg** [graphile/postgraphile#1446]
### Summary

Is it safe to connect postgraphile to a production database without knowing anything about graphql or databases in general? i have a access to a prod databse that i would like to see how data is visualized using graphql , but im concerned if there is anything that postgraphile makes changes to the database under the hood. Thanks in advance!

### Additional context

Noob when it comes to databases 🤦‍♂️

**Comment by benjie** [comment]
If you use a postgresql role with limited permissions then you can be certain it won’t cause any issues (because of PostgreSQL’s built in security), but I’m assuming that’s not an option for you. Watch mode installs some event triggers (so don’t use it on a production DB), but everything else should be safe in core. I can’t speak for third-party plugins though.
