### ISSUE TITLE
How to "encapsulate" or add a named scope around postgraphile queries?

### ISSUE THREAD

**Issue by MarkLyck** [graphile/postgraphile#1622]
I am trying to create a graphQL "api gateway" where I'm combining all of my data sources into one graph API.

Everything else works just fine but postgraphile is causing some headaches and many hours wasted on this 1 error.

I want my graphQL api to be queried something like this:

```
// GOOD ✅
query {
  restApi1 { ... }
  restApi2 { ... }
  cubejsApi { ... }
  postgraphile { ... }
}
```

I want to avoid this mess where my hundreds of postgraphile queries are mixed between my other nicely scoped queries:

```
// BAD 👎
query {
  allTableRows1 
  ...
  restApi1 { ... }
  allTableRows27 { ... }
  ...
  restApi2 { ... }
  ...
  allTableRows98 { ... }
  ...
  cubejsApi { ... }
  allTableRows102 { ... }
  allTableRows102 { ... }
}
```

Where each data source is encapsulated with a namespace. As it would be incredibly frustrating to have random types and resolvers from different APIs and all of my postgres tables ALL in the root level query... That would be an unmaintainable mess.

So far I've been trying to accomplish this with the use of graphql-mesh: https://www.graphql-mesh.com, and I am able to encapsulate all of my other data sources without any issues. Postgraphile is the only one causing the following error:

```
{
  "data": null,
  "errors": [
    {
      "message": "Interface field Node.nodeId expected but Query does not provide it."
    }
  ]
}
```

Obviously Node.nodeId is something postgraphile is generating and expecting?

I'm assuming this is because the graphQL mesh "encapsulate transformation" isn't getting everything 100% correct... So instead of using graphql-mesh to encapsulate it.

How can I encapsulate it with "vanilla" postgraphile?

I don't see any plugins or any settings that lets you namespace the root level query? Is this really not supported in postgraphile?

In my frustration with this, I tried switching to Prisma, and with Prisma I was able to namespace it without any issues. But it is my understanding that postgraphile has a significantly better performance than Prisma, and Prisma is not directly supported in graphql-mesh like postgraphile is so I'd like to use postgraphile of course.

Any help would be appreciated.

**Comment by benjie** [comment]
You've got similar needs to the Gatsby integration; check out the plugins we wrote for that:

https://github.com/graphile/gatsby-source-pg/tree/main/lib

Namely:

1. Remove the 'Node' interface from the 'Query' type (`RemoveNodeInterfaceFromQueryPlugin.js`)
2. Rename the 'Query' type (`RenamedQueryPlugin`)

**Comment by KarenPainter** [comment]
We are trying to do something similar. We have a federated Apollo graph and would like to enclose the PostGraphile queries and mutations inside [a namespace](https://www.apollographql.com/docs/technotes/TN0012-namespacing-by-separation-of-concern/) so they don't clutter up the root.

Ideally, our composed graph would look like what the original poster requested.
```
root
-- Query
---- restApi1 
---- restApi2
---- postgraphileSubgraph
-- Mutation
---- restApi1 
...etc
```
I was able to use the plugins mentioned above, and we're getting a little closer. Now the structure is:
```
root
-- Query
---- restApi1 
---- restApi2
-- PostGraphileQuery
...etc
```
Or, at least, it would be if the Apollo router could handle this unusual root query object, but it apparently doesn't. (The plugin we're using to enable federation is [postgraphile-federation-plugin](https://github.com/mgagliardo91/postgraphile-federation-plugin). 

So rather than renaming the Query root, we'd like to add an additional layer below Query that all the postgraphile stuff is connected to. Not sure if that can be done, but if anyone has guidance, please let me know. I'm definitely a newbie (didn't know that PostGraphile existed a week ago), so it's possible I'm missing something very obvious.

**Comment by KarenPainter** [comment]
So far I've been able to add the namespace and the necessary resolvers by adding the plugin below to the `prependPlugins` options. But I think that's the easy part. 🙂 I think the next step would be to remove the type definitions for `PostGraphileQueries` and `PostGraphileMutations` from this plugin, and instead add them via some kind of builder hook that somehow alerts PostGraphile that all the queries and mutations should be added to these types, rather than to the root query object. But I am not sure how to do that.

```
const { makeExtendSchemaPlugin, gql } = require('graphile-utils');

export const AddNamespacePlugin = makeExtendSchemaPlugin(() => {

  return {
    typeDefs: gql`
      extend type Query {
        postGraphile: PostGraphileQueries
      }
      extend type Mutation {
        postGraphile: PostGraphileMutations
      }
      type PostGraphileQueries {
        thing: String # This is just a placeholder. Ideally, this would have all the PostGraphile queries inside it.
      }
      type PostGraphileMutations {
        thing: String
      }
    `,
    resolvers: {
      Query: {
        postGraphile: async (): Promise<{}> => ({}),
      },

      Mutation: {
        postGraphile: async (): Promise<{}> => ({}),
      },
    },
  };
});
```

**Comment by benjie** [comment]
@KarenPainter You want to skipPlugins the QueryPlugin and MutationPlugin, and replace them with your own.

See: https://github.com/graphile/graphile-engine/blob/v4/packages/graphile-build/src/plugins/QueryPlugin.js

The `isRootQuery` here:

https://github.com/graphile/graphile-engine/blob/3daa9cdae93d642b4cc72c8e80a534850c13d00b/packages/graphile-build/src/plugins/QueryPlugin.js#L56

tells the system that's where to add stuff.

The schema extensions here:

https://github.com/graphile/graphile-engine/blob/3daa9cdae93d642b4cc72c8e80a534850c13d00b/packages/graphile-build/src/plugins/QueryPlugin.js#L64

adds that as the query root to the GraphQL schema. You want those to be separate.

Please note that you **should not namespace** GraphQL mutations in the way originally proposed - all mutations should go into the same root mutation namespace. Please [trust me on this](https://github.com/graphql/graphql-spec/graphs/contributors).

**Comment by KarenPainter** [comment]
Thank you for the guidance, Benjie! I'm making progress.

First, I am certainly inclined to trust you about the mutations, but I think the "trust me on this" link is going to the wrong place. Could you please check it? I assume it should link to an explanation of all the hazards.

As for the code, I think I'm getting close. The first plugin below makes my schema look exactly like I had hoped (minus the mutations -- queries only). The problem is that all queries simply return
```
{
  "data": {
    "postgraphile": null
  }
}
```
I think the problem is that I'm missing a resolver to pass the request down to the namespace level. I try to add it with a second plugin (probably not the best way), but it doesn't seem to have any effect. (Both plugins are listed in `prependPlugins`, and I'm skipping the standard Query, Mutation, and Subscription plugins.)

Any suggestions are much appreciated!

**Comment by benjie** [comment]
Your rootQuery postgraphile field needs a resolver, return $$isQuery from it.

As for mutations, the GraphQL spec itself states that the top level selection set performs side effects/etc, and is executed serially. Selection sets deeper run in parallel. Namespacing mutations is not safe. https://spec.graphql.org/draft/#sec-Mutation

**Comment by benjie** [comment]
Ohhh I see that’s what your second plugin is attempting to do. You should add the resolver in the first plugin, right next to where the type of the field is defined.

**Comment by KarenPainter** [comment]
Thank you, Benjie! You've been so helpful! It seems to be working correctly now.
I'm posting the finished version in case it helps someone else. 

```
import type { Build, SchemaBuilder } from 'graphile-build';

export type BuildExtensionQuery = {
  $$isQuery: Symbol,
};

export default (async function QueryPlugin(builder: SchemaBuilder, { namespace = 'transactionalDb' }) {
  builder.hook(
    'build',
    (build: Build): Build & BuildExtensionQuery =>
      build.extend(
        build,
        {
          $$isQuery: Symbol('isQuery'),
        },
        'Extending Build',
      ),
  );
  builder.hook(
    'GraphQLSchema',
    (schema: {}, build) => {
      const {
        $$isQuery,
        newWithHooks,
        extend,
        graphql: { GraphQLObjectType },
        inflection,
      } = build;
      const namespacedQueries = newWithHooks(
        GraphQLObjectType,
        {
          description: 'The namespace query type which encloses all the postGraphile queries.',
          name: inflection.upperCamelCase(`${namespace}Queries`),
          isTypeOf: (value: any, _context: any, info: any) =>
            info.parentType == null || value === $$isQuery,
          fields: {},
        },
        {
          __origin: 'a child of the query type, and the container for all other queries (is RootQuery)',
          isRootQuery: true,
        },
      );
      const rootQuery = newWithHooks(
        GraphQLObjectType,
        {
          description: 'The root query type which contains the graph\'s namespaces',
          name: inflection.builtin('Query'),
          isTypeOf: (value: any, _context: any, info: any) =>
            info.parentType == null || value === $$isQuery,
          fields: () => ({
            [namespace]: { type: namespacedQueries, resolve: () => $$isQuery },
          }),
        },
        {
          __origin: 'replacement for graphile-build built-in root query type (is not RootQuery)',
          isRootQuery: false,
        },
      );
      return extend(
        schema,
        {
          query: rootQuery,
        },
        'Adding \'Query\' type to Schema',
      );
    });
});
```
