### ISSUE TITLE
Accessing `pgClient` in hooks for `explain` data

### ISSUE THREAD

**Issue by shellscape** [graphile/postgraphile#1642]
### Summary

We're using the embeddable Apollo Explorer in place of GraphiQL (for a number of reasons that are off topic) and we'd like to add the `explain` data onto result data.

### Additional context

We already know that we can use the `postgraphile:http:end` hook to mutate result data. However, we're hitting a wall trying to find the right hook or right method to access `pgClient._explainResults`. We're starting postgraphile with `allowExplain: true` fwiw.

I've tried to trace through contexts to figure out where postgraphile might be exposing that, but I'm coming up empty. (It's a bit dizzying trying to follow what is sent where and how contexts are constructed, without being intimately familiar with it).

Any pointers to solve this one?

**Comment by benjie** [comment]
I think you need to set a header; if you run postgraphile CLI with explain enabled and use the network tools you should be able to spot it (I’m not at a computer rn) 👍

**Comment by shellscape** [comment]
Ah we're running using the lib programmatically.

**Comment by shellscape** [comment]
Ah I follow you now, and I know where that is in code. Can you recall where in the request pipeline  (or hook)  that should be set?

**Comment by benjie** [comment]
Turns out it's `X-PostGraphile-Explain: on`; set here in the GraphiQL `fetcher`: https://github.com/graphile/postgraphile/blob/a33712580ae3304d9f68cedaf4816a0661dfbad1/postgraphiql/src/components/PostGraphiQL.js#L376

Which results in `explain` being set to true on the withPostGraphileContext options: https://github.com/graphile/postgraphile/blob/ed6ecb4596088120969795a9ec30cb625ef93eae/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L152

Which then uses the `startExplain` / `stopExplain` methods that we patch onto the Postgres client:

https://github.com/graphile/postgraphile/blob/263ba7477bc2133eebdf89d29acd0460e58501ec/src/postgraphile/withPostGraphileContext.ts#L481-L508

(Note that this will not work with schema-only usage because we don't mod the postgres client with schema-only usage.)
