### ISSUE TITLE
Generate GraphQL schema from DDL or model objects

### ISSUE THREAD

**Issue by tangenttechno** [graphile/postgraphile#1667]
### Summary

Postgraphile listens to  Postgres database events and generates the corresponding Graphql which is working great. Is it possible to pass a DDL for example create table script or a model object(entity) to any of the postgraphile function and generate Graphql against the same?

**Comment by benjie** [comment]
There are cache features you may be looking for; see `readCache` and `writeCache` in https://www.graphile.org/postgraphile/usage-schema/

Failing that, no we don't support that in PostGraphile Version 4.

**Comment by tangenttechno** [comment]
@benjie   Thank you for the quick response. My intention is to get control over generated graphql, I mean the code will create a database table and then call Postgraphile method to generate Graphql. readCache and writeCache looks interesting, can we create these cache file programmatically, that is after creating database table, write the table details to the cache file and call createPostGraphileSchema method with readCache location as the cache file we wrote earlier?

**Comment by benjie** [comment]
The intent is that you point PostGraphile at your DB and tell it to write a cache, then you shut down PostGraphile (or it does it itself). Later you run PostGraphile passing `readCache` and it should use the cache rather than redoing introspection. It is not intended that you can populate the cache yourself, though it's just JSON data if you don't give it consistent data with what it expects then you may get unexpected output.

**Comment by tangenttechno** [comment]
@benjie  Thank you. perfectly clear.

**Comment by phxgbl** [comment]
@benjie This would be a good feature. I guess this is implemented in Hasura in a different way, I mean we can create tables(execute DDL) using hasura API , and hasura will be creating graphql against the same and return instant feedback. Please consider this feature for next release.

**Comment by benjie** [comment]
@phxgbl Maybe I’m missing something, but what it seems like you describe we have had for longer than Hasura has existed, except we don’t need a custom API for it: create your tables (using any tool you like, there are hundreds) and if you’re running PostGraphile in watch mode the GraphQL API will update immediately and be reflected immediately in GraphiQL. Here’s a GIF I made of it in 2017:

https://twitter.com/benjie/status/903289965211213824?s=46&t=WsoOKIybuHgjR9Nh5zGXGg

Since then we’ve built Graphile Migrate which gives a watch mode to writing migrations, giving you the above feel throughout your application development.

**Comment by phxgbl** [comment]
@benjie yes, postgraphile is unique and a very powerful tool for fast and dynamic development. What i meant was, if the above said feature is also added, that can be useful for certain scenarios. Thank you for this amazing product.

**Comment by benjie** [comment]
But what you're describing seems to be different to what the issue itself is requesting - you seem to be describing a feature we already have?
