### ISSUE TITLE
Missing subscriptionAuthorizationFunction for custom subscriptions, alternatively uncooperative pluginHooks with graphql-codegen

### ISSUE THREAD

**Issue by LahTeuto** [graphile/postgraphile#1670]
During development using postgraphile and graphql-codegen in our organization, we encountered an issue trying to tighten the security around our subscriptions and reduce possible information leaks.

It seems to be impossible to specify a subscriptionAuthorizationFunction using custom subscriptions (not simpleSubscriptions!), and that fact is not clearly communicated in the documentation in our opinion.

After switching to simpleSubscriptions, we encountered another problem, namely that because simpleSubscriptions injects the typedefs for the "listen" field through a pluginHook, which is ignored/not even executed when graphql-codegen autogenerates a schema, graphql-codegen can't find the Subscription and ListenPayload types and throws a really difficult to debug error.

It would be really nice if the subscriptionAuthorizationFunction would be used for custom subscriptions too if it's specified - custom subscriptions play nice with graphql-codegen too.

**Comment by benjie** [comment]
> It seems to be impossible to specify a subscriptionAuthorizationFunction using custom subscriptions (not simpleSubscriptions!), and that fact is not clearly communicated in the documentation in our opinion.

This PR should clarify that `subscriptionAuthorizationFunction` is simple subscriptions only: https://github.com/graphile/graphile.github.io/pull/335

When you use custom subscriptions you can add _any authorization method you want_ because you are fully in control of the subscription. Have a look at the first example in the custom subscriptions page: https://www.graphile.org/postgraphile/subscriptions/#custom-subscriptions

```js
const currentUserTopicFromContext = async (_args, context, _resolveInfo) => {
  if (context.jwtClaims.user_id) {
    return `graphql:user:${context.jwtClaims.user_id}`;
  } else {
    throw new Error("You're not logged in");
  }
};
```

The topic callback is an async function that is passed the args, context and resolveInfo and can do anything it wants before either returning the string topic to use or throwing an error (because access is denied). It can even use `await context.pgClient.query('...')` to call a database function if that's your preference.

> After switching to simpleSubscriptions

I strongly advise you stick with custom subscriptions.

> because simpleSubscriptions injects the typedefs for the "listen" field through a pluginHook, which is ignored/not even executed when graphql-codegen autogenerates a schema, graphql-codegen can't find the Subscription and ListenPayload types and throws a really difficult to debug error.

It sounds like you have something custom going on for exporting your GraphQL schema, consider either using PostGraphile's `exportGqlSchemaPath` option or performing the introspection directly against your GraphQL server to generate the schema file for GraphQL Code Generator to use. Perhaps you're using `createPostGraphileSchema` which does not support pluginHook and thus cannot support subscriptions in this way?

**Comment by LahTeuto** [comment]
Thank you for the thorough response and updating the docs, that was very helpful. Using a query through the pgClient provided in the context works beautifully.

We are indeed using `createPostGraphileSchema`, which, now that we're using custom subscriptions as you suggested, works without issue again.
