### ISSUE TITLE
Using `pg-pubsub` in schema-only mode

### ISSUE THREAD

**Issue by holeya** [graphile/postgraphile#1679]
### Summary

I'm using PostGraphile in [schema-only mode](https://www.graphile.org/postgraphile/usage-schema/). However [custom subscriptions](https://www.graphile.org/postgraphile/subscriptions/#custom-subscriptions) don't seem to work, for two reasons:

* `createPostGraphileSchema` takes options of type `PostGraphileCoreOptions`. This type doesn't have a `pluginHook` field for adding the `@graphile/pg-pubsub` plugin (this field is present on `PostGraphileOptions`, which extends `PostGraphileCoreOptions`).

* If I ignore that and set `pluginHook` anyway, the `graphql` module throws when subscribing, with the error message `Subscription field must return Async Iterable. Received: undefined.`

It's possible to work around this issue by creating a PostGraphile HTTP request handler, and then getting the schema from there:

```
- const schema = await createPostGraphileSchema(...)
+ const schema = await postgraphile(...).getGraphQLSchema()
```

But that seems a bit convoluted, so I'm curious if I'm missing something here or if that's just a PostGraphile idiosyncrasy.

### Additional context

Latest `postgraphile` version, 4.12.11.

I'm using PostGraphile in schema-only mode because I freaked out a little when I discovered that PostGraphile's HTTP handler was extending the Node HTTP server to accept websocket connections. Schema-only mode offers a separation of concerns that's very valuable for apps that prefer to fully control the network side.

PostGraphile is absolutely fantastic btw. Thank you :heart:

**Comment by benjie** [comment]
Schema only mode doesn't support `pluginHook` because `pluginHook` is to define server and command line plugins, and in schema-only mode you explicitly don't have a PostGraphile server/CLI.

However, `pluginHook` can also add to your configuration; for example it can add to `appendPlugins`, etc; which is the issue you're facing here.

Since pluginHook plugins are just simple objects with predefined methods, you can try just calling the relevant hook yourself, in this case it would be this one:

https://github.com/graphile/graphile-engine/blob/v4/packages/pg-pubsub/src/index.ts#L60

**Comment by holeya** [comment]
Just tried it and it works great. Thank you!
