### ISSUE TITLE
createPosgraphileSchema() generates schema based on pg role or not? Also seems additional mutations are generated other than pg sql functions that created

### ISSUE THREAD

**Issue by dollarbear81** [graphile/postgraphile#1728]
Just started building app on node.js and express, have some doubts about the usage of createPosgraphileSchema():

1. the schema options seems not working properly, it always scan the entire db as what I can see from the output json file
2. does the graphql schema generation related to the pgDefaultRole? I have put different db role, but seems getting same schema?
3. Upon checking the mutations, I see more than expected using below, not sure if thats normal behaviour
{
  __schema {
    mutationType {
      fields {
        name
      }
    }
  }
}

Thanks in advance if anyone has experienced similar or has got solution on above.

**Comment by benjie** [comment]
> the schema options seems not working properly, it always scan the entire db as what I can see from the output json file

The schema options work correctly. Schema mode works perfectly fine, it's what library mode uses internally.

> does the graphql schema generation related to the pgDefaultRole? I have put different db role, but seems getting same schema?

No, that option is only for runtime not for schema build time. Imagine you connect to database with role AUTHENTICATOR and your support roles ANONYMOUS, USER and ADMIN. pgDefaultRole will likely be set to ANONYMOUS so that users who are unauthenticated will only be able to do things ANONYMOUS can do. However, the schema itself needs to know everything ANONYMOUS, USER and ADMIN can do - hence it uses the AUTHENTICATOR role for introspection. This should be a reduced-privilege role (ideally using `NOINHERIT`) that is merely capable of switching into one of the other three roles.

> Upon checking the mutations, I see more than expected using below, not sure if thats normal behaviour

I've no idea what you're getting at here. The introspection query is like a tiny subset of the one GraphiQL uses; it returns the field names of all the (non-deprecated) fields on the mutation type - same as you would see in GraphiQL. If you're seeing different results in GraphiQL for postgraphile library mode vs your schema-mode usage, then you have configured your schema-mode usage differently or used a different connection string or similar.

> Also seems additional mutations are generated other than pg sql functions that created

Yes, in addition to the Postgres functions, CRUD mutations are created. You can disable this via an option.

**Comment by benjie** [comment]
`ARRAY_OF_SCHEMA` should be an array of the names of the schemas in the database, e.g. `['app_public', 'app_readonly']`
