### ISSUE TITLE
Provide an option like externalGraphqlRoute for the CLI usage

### ISSUE THREAD

**Issue by stakaz** [graphile/postgraphile#1729]
### Feature description

Provide an option like externalGraphqlRoute for the client usage.

### Motivating example

Curently I cannot use the client behind a reverse proxy and serve graphql AND graphiql on a suburl.

I am trying to start postgraphile with pm2 to kame a persistent API endpoint in the most simple way.

graphql can be served on a suburl without any problems but graphql searches for graphql under root and therefore no endpoint is availible).

We have similar cases in our working group and externalGraphqlRoute provides a simple solution to this problem.

But there is no client option for this now.

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
```ts
  // The URL to the GraphQL endpoint for embedding into the GraphiQL client.
  // We attempt to infer this (for many servers it is the same as
  // `graphqlRoute`), but you may need to specify it manually if you mount
  // PostGraphile behind a URL-rewriting proxy, or mount PostGraphile on a
  // subpath in certain Node.js servers.
  /* @middlewareOnly */
  externalGraphqlRoute?: string;
```

I don't understand... `externalGraphqlRoute` is exactly for this usage? It's to tell GraphiQL (the client) what URL it needs to use to reach the GraphQL API. What do you mean "there's no client option for this now"?

**Comment by stakaz** [comment]
Hello, I mean, that I cannot provide this option by calling postgraphile in a terminal. This option is only available if I use postgraphile as a library. But that is much more work for 'just have an automatic api for a database with one call'.

Jul 6, 2023 09:21:01 Benjie ***@***.***>:

**Comment by stakaz** [comment]
Here is an example: 

```
postgraphile -c "postgres://myserver/mydatabase" -p 1234 --enhance-graphiql --externalgraphqlroute /sub/url
```

And then redirect `mydomain.com/sub/url` to `localhost:1234/`.

**Comment by benjie** [comment]
Oh, right... That was never intended to be a CLI option since it's quite advanced (very few people use it). Adding every single option that's available via a CLI flag would be overwhelming! (We already have too many as it is.)

If you don't want to switch to library mode, you need to use a `.postgraphilerc.js` file: https://www.graphile.org/postgraphile/usage-cli/#rc-file-options 

Though it's not officially documented there, it looks like we splat any unprocessed options out and pass them through to the PostGraphile middleware:

https://github.com/graphile/postgraphile/blob/4af2bb74def4b31b6904424631331c105fcdaa7c/src/postgraphile/cli.ts#L709

So it should work.
