### ISSUE TITLE
disableDefaultMutations: true is not disabled in postgraphile UI for large database

### ISSUE THREAD

**Issue by prabhanjali11** [graphile/postgraphile#1742]
### Summary

I am having a large database which contains around 1200 tables and the database size may increase later. while I am creating my postgraphile UI,  I am using disableDefaultMutations: true  option as I am using Postgraphile as a library. Even though if I use it, I am facing the above issue as it is not disabled in the UI.

### Expected results

- I need to disable my postgraphile mutation option

### Actual results

Postgraphile mutations are enabled eventhough if I disable them
![image](https://github.com/graphile/postgraphile/assets/143176104/d1dda8ea-5087-4e2d-af9a-3a0ee450ae50)

![image](https://github.com/graphile/postgraphile/assets/143176104/e76c0218-7db6-46a5-845b-ad62769c47fb)

**code:**

![image](https://github.com/graphile/postgraphile/assets/143176104/f14db94e-5184-40ef-b6f1-36d51bd24ede)

**Comment by benjie** [comment]
You've misunderstood what `disableDefaultMutations: true` does. It disables the default CRUD mutations that PostGraphile builds for you, it doesn't disable your _custom_ mutations that you've added via volatile database functions. That's why your volatile function `getresources` is there but none of the CRUD mutations are.

To disable _all_ mutations, you need to skip the MutationPlugin. In V5 that'd be `disablePlugins: ['MutationPlugin']`. In V4 I don't remember exactly, but maybe `skipPlugins: [require('graphile-build').MutationPlugin]`?

**Comment by prabhanjali11** [comment]
but I haven't added any of the custom Mutations, then why did ```getresources``` got enabled?

**Comment by benjie** [comment]
Getresources is a volatile database function you have defined or that exists in your database.

skipPlugins of the MutationPlugin SHOULD disable mutations because it literally results in the Mutation type not being created. If it’s not working you may see an error in the console telling you why (something like: tried to skip a plugin that wouldn’t have been used), in which case you’re importing the plugin from the wrong place for your setup.

**Comment by benjie** [comment]
If you cannot accomplish the skipPlugins in V4 you might want to try V5 instead since this now just uses a string so it's a lot harder to get wrong.

**Comment by prabhanjali11** [comment]
No, I have actually tried both pof them, but they did'nt work.
This is the version I am using 4.13.0
![image](https://github.com/graphile/postgraphile/assets/143176104/13828c44-5b55-4e4e-b6ad-cde6d14792e5)
will this come under V4 or V5

**Comment by prabhanjali11** [comment]
@benjie thanks for your help. ```skipPlugins: [require('graphile-build').MutationPlugin]``` this worked. I had placed it in a wrong place.
