### ISSUE TITLE
Support logging in as postgres user

### ISSUE THREAD

**Issue by martinheidegger** [graphile/postgraphile#332]
By default all requests are done using the user specified when starting postgraphql. In my case I would like to be able to have the default user only be a "public" user while any write operation would need a login. As far as I could tell this is not yet supported... Right?

**Comment by benjie** [comment]
I use the JWT functionality to change the database role and set various config settings. (If you go this route, I highly recommend using PG9.6+ so you get the second option `missing_ok` of [current_setting(name, missing_ok)](https://www.postgresql.org/docs/9.6/static/functions-admin.html).)

Read more about it in [Caleb's PG JWT spec](https://github.com/calebmer/postgraphql/blob/master/docs/pg-jwt-spec.md)

**Comment by martinheidegger** [comment]
Actually that is missing my point a little 😅  When starting the `postgraphql` server it uses a user/password to access the data. The default user should not allowed to do anything except figure out the database structure. For any operation the user would need to call a `login(user, password)` API that sets up a new database connection with said credentials.

**Comment by benjie** [comment]
Sorry, I should have prefixed my comment with "This isn't exactly what you've asked for, but..."!

The functionality is similar, in that you can use postgresql roles and the default role has different (lower) privileges. The major difference is that the default user needs to be able to switch to be one of the other users via `SET LOCAL ROLE` (like `su`) and for that I think the user needs to be granted the other roles (and is thus higher privileged than you would like). Note, however, that by using [`NOINHERIT`](https://www.postgresql.org/docs/9.6/static/sql-createrole.html) when granting the roles, the default user cannot leverage any of those roles without first switching into them which postgraphql is very careful to protect.

It's not as secure as having a new database connection for each user with their own password, but it is closer than you might at first think.

**Comment by calebmer** [comment]
You may also be looking for the `pgDefaultRole` option which allows you to specify the role when no token is provided 😊

This option is demonstrated in the [forum example tutorial](https://github.com/calebmer/postgraphql/blob/master/examples/forum/TUTORIAL.md) with the `forum_example_anonymous` role.

**Comment by benjie** [comment]
Our current implementation for this enables connection pooling; if we were to implement direct Postgres user login then we'd not be able to use this. Further we'd be opening the database to root logins, which may need some additional protections (though Postgres can handle these itself by only granting login from the IP associated with the PostGraphQL server to certain users).

I'd be open to a PR that adds this functionality behind a CLI flag since it seems in line with the ethos of turning your database into a GraphQL endpoint and if well controlled it's more secure (in the event of a security flaw in PostGraphQL there'd be no transaction to "escape" from; you can only do what your user account is allowed to; you can't take another role via a stray `set` command). Do you agree @calebmer?

**Comment by calebmer** [comment]
I’m a little confused why a default role with `pgDefaultRole` would not be sufficient in this case? I agree that not having a default role can be a big problem, but we do have a default role feature.

**Comment by calebmer** [comment]
And I should probably add a default role that is exclusive from the user used to connect to Postgres 😊

**Comment by benjie** [comment]
@calebmer Martin's looking for a fresh database connection logged in using the users *database* credentials; we use application-level credentials. In the event of an SQL injection attack in our current system, the user could trigger `set "jwt.claims.user_id" to '1';` or similar and become any user they like. If, instead, it was a fresh database connection logged in using the user provided credentials it would mean if there were SQL injection the user would still only be allowed to do what the GRANTs and Row-Level Security allowed for that specific database user, without the ability to become a different user.

Obviously our existing implementation has a lot of advantages (not least connection pooling) but in the event of a breach Martin's approach would be safer.

**Comment by calebmer** [comment]
@benjie thanks for the clarification. I’m pretty confident that PostGraphQL is strong against any SQL injection attack attempts given how we construct SQL. If we really wanted to remove the chance of introducing an accidental SQL injection attack then we could even remove: https://github.com/calebmer/postgraphql/blob/fe84f9def87092c203d24ded4d1fdc2a949d94a5/src/postgres/utils/sql.ts#L12

I do think this is an interesting thing to enable, however, if we allowed a `pgauth` or similar property in JWTs. It would require some refactoring of our Postgres connection/pooling code in order to create new connections at runtime.

**Comment by benjie** [comment]
I'm confident too, but security is all about layers and controlling what would happen if one layer is compromised; for example it might be a bug in node-pg that opens the connection to an SQL injection attack.

**Comment by martinheidegger** [comment]
What @benjie talks about was my initial concern, I also first thought about the doing it on a connection level but since learned that [postgres supports users/session](https://www.postgresql.org/docs/8.1/static/sql-set-session-authorization.html). But also, I learned that Postgraphql [uses the defaultRole](https://github.com/calebmer/postgraphql/blob/939a91ed20fc183bcd0fc8367a7b6af891e6a2de/src/postgraphql/http/createPostGraphQLHttpRequestHandler.js#L392) for requests and my initial task was to have two different roles: One for introspection (with enough access to inspect/generate the schema) and one that is used for regular requests (query, mutation). Since I would like to have the documentation be readily available but the default access be denied.

**Comment by calebmer** [comment]
@martinheidegger I’d be interested in seeing what that looks like, and it seems like a very reasonable security feature to implement.

**Comment by benjie** [comment]
I'm going to close this because there's been no movement on it. I'm happy with [the authenticator / visitor setup I use](https://github.com/graphile/examples/blob/bb0a3a24b83dcd71706d2134abba8c6373f1c169/setup.sh#L97-L114) and it's possible to implement the lower level access yourself if you need to by writing your own wrapper around the GraphQL schema.

If there's more interest in this, however, then I'm open to re-opening - let me know in the comments below (one of the rare times 👍  comments on GitHub are okay!)
