### ISSUE TITLE
how to implement a viewer for postgraphql endpoint

### ISSUE THREAD

**Issue by lifeiscontent** [graphile/postgraphile#567]
Hey @benjie I recently came across an article about authentication and using the viewer object in a graphql endpoint to deal with authorization / authentication by token.

How would I go about creating a viewer in postgraphql? Is there a way to extend the graphql endpoint by passing in an additional part of a schema or how would this work?

**Comment by benjie** [comment]
I'm on a bus right now, but does this help? https://www.graphile.org/postgraphile/extending/ (replace postgraphile with postgraphql@next in your head)

**Comment by lifeiscontent** [comment]
@benjie is there a way to use append plugins using Postgres as a middleware?

**Comment by hmaurer** [comment]
This is an old issue, but in the interest of providing an answer before closing it, I think this can be done with a stored procedure (in fact this is what I am doing myself), and possibly a custom type if your viewer does not map directly to a database table (e.g. user). c.f. https://www.graphile.org/postgraphile/procedures/#query-procedures

@benjie this issue is quite old; it can probably be closed for now? Perhaps making a note that since the concept of a "viewer" is used quite a bit in GraphQL/Relay, some documentation on the website referring to this explicitly (by mentioning it can be implemented using a custom query) could be desirable.

**Comment by benjie** [comment]
Flagged it for adding to the docs.

**Comment by benjie** [comment]
I'm no longer requiring the add-to-docs issues to be open (we can remove the add-to-docs label when we've done it instead); so closing this 👍

**Comment by kirkbross** [comment]
Old and closed... but if you happen to see this, how do I get Postgraphile to create the Viewer type in my schema for use with Relay? I'm not sure which links are relevant any more.

**Comment by benjie** [comment]
You can add a field with, for example, `makeExtendSchemaPlugin`. I don't think Relay requires this field any more?
