### ISSUE TITLE
postgresql enum that starts with number causes error

### ISSUE THREAD

**Issue by yeedle** [graphile/postgraphile#570]
One of the values of an enum in my postgresql database starts with a number (e.g. `CREATE TYPE seasons AS enum ('3 weeks', '5 weeks', '12 weeks')`. When trying to connect to this database with postgraphql, I get the following error:

```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "3_WEEKS" does not.
    at assertValidName (/usr/lib/node_modules/postgraphql/node_modules/graphql/utilities/assertValidName.js:44:11)
    at /usr/lib/node_modules/postgraphql/node_modules/graphql/type/definition.js:632:42
    at Array.map (native)
    at defineEnumValues (/usr/lib/node_modules/postgraphql/node_modules/graphql/type/definition.js:631:21)
    at new GraphQLEnumType (/usr/lib/node_modules/postgraphql/node_modules/graphql/type/definition.js:549:20)
    at Object.enum (/usr/lib/node_modules/postgraphql/build/graphql/schema/type/getGqlOutputType.js:70:55)
    at callSwitchTypeCase (/usr/lib/node_modules/postgraphql/build/interface/type/switchType.js:19:43)
    at Object.switchType (/usr/lib/node_modules/postgraphql/build/interface/type/switchType.js:6:42)
    at createGqlOutputType (/usr/lib/node_modules/postgraphql/build/graphql/schema/type/getGqlOutputType.js:15:24)
    at /usr/lib/node_modules/postgraphql/build/graphql/utils/memoize.js:52:35
```

Is changing my postgresql enum the only way to get around this issue? (that would be quite the hassle).

**Comment by benjie** [comment]
This is solved in postgraphql@next by prefixing with an underscore; see #506 for more info on `@next`

**Comment by korenzerah** [comment]
Hello,
I got this error by having enums in another language (Hebrew). Is there a workaround for this issue in my situation?

**Comment by benjie** [comment]
Yes! You can override the inflector that converts PostgreSQL enums to GraphQL; it's very easy to do:

```js
// CustomEnums.js
const { makeAddInflectorsPlugin } = require('graphile-utils');
module.exports = makeAddInflectorsPlugin({
  enumName(pgValue) {
    return hebrew2latin(pgValue);
  }
});
```

```bash
postgraphile -c my_db --append-plugins `pwd`/CustomEnums.js
```

I'm afraid the `hebrew2latin` function (which takes a string and returns a string) is left as an exercise for the reader!

Read more about inflection here:

https://www.graphile.org/postgraphile/inflection/

**Comment by korenzerah** [comment]
@benjie does it mean I can't return hebrew values to the client?

**Comment by davoam** [comment]
Imho, this is a big downside. Let's say we have a specification (and we can't change it) which says type `CarColor` has the following values `Color.red`, `Color.blue`. 

We create in postgres the following  type 
```
CREATE TYPE "car_color" AS ENUM (
  'Color.red',
  'Color.blue'
);
```
And we can't return to clients values `Color.red` or `Color.blue` because there is a dot and it's not allowed according to the provided regex pattern

@benjie could you please clarify is there any ways to overcome this? Is there any way to still specify all the possible values for a column and return one of to a client if it is needed?

**Comment by benjie** [comment]
GraphQL enums are an abstraction; it shouldn't matter to the frontend what the backend value of an enum is; e.g. in the frontend you might refer to "RED, GREEN and BLUE" but in the backend you might refer to "0, 8 and 16" since these are the "bit-offsets" in a 24-bit RGB value - there's no reason these have to overlap.

You can override the enumName inflector to allow any enum values be converted to the GraphQL acceptable regexp. Here's the default inflector:

https://github.com/graphile/graphile-engine/blob/dc1951c0ae19f82d2483f0d57ee6fb29d01aec24/packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js#L476-L556

And here's the plugin we use in postgraphile-core to make it fully uppercase:

https://github.com/graphile/graphile-engine/blob/dc1951c0ae19f82d2483f0d57ee6fb29d01aec24/packages/postgraphile-core/src/index.ts#L146-L157

You could do a similar inflector plugin:

```ts
const { makeAddInflectorsPlugin } = require("graphile-utils");

module.exports = makeAddInflectorsPlugin({
  enumName(value: string) {
    return previous.call(this, value.replace(/\./g, '_'));
  },
}, true);
```

https://www.graphile.org/postgraphile/make-add-inflectors-plugin/

**Comment by davoam** [comment]
@benjie, thanks for the quick response and code snippet 
> it shouldn't matter to the frontend

In case when front-end needs to get exactly the same value which back-end uses it matters. Otherwise, front-end needs to do transformation on its own (example, if I received `Color_red` it actually means `Color.red`

**Comment by benjie** [comment]
If the client cares what the underlying storage value is, then `enum` is not the correct type to use. Enum is an abstraction. Use `String` or similar.
