### ISSUE TITLE
Any plans for request throttling?

### ISSUE THREAD

**Issue by chadfurman** [graphile/postgraphile#572]
Most of the time a single IP address should not be hitting the API more than 100 times a minute.  Anything more than that would be nice to discard.  Likely a follow-up to being able to access the IP within a plugin.  

https://github.com/postgraphql/postgraphql/issues/299  HTTP Request in postgraph
https://github.com/postgraphql/postgraphql/pull/460  Exposing headers
https://github.com/postgraphql/postgraphql/issues/501  Get JWT, IP logging in plugins...

**Comment by benjie** [comment]
I think this specific functionality would be better implemented via a separate concern - e.g. at the proxy or webserver layer (nginx) or if necessary you can achieve it via an express middleware (there's so many to choose from!)

I do not want to extend the projects scope to include throttling out of the box since it can so easily be implemented at a higher tier - it's just one more thing to maintain. I'd definitely be happy if someone wanted to write a guide on how to implement throttling on the website though!

**Comment by chadfurman** [comment]
Makes sense :+1:
