### ISSUE TITLE
Disable auto camel casing?

### ISSUE THREAD

**Issue by gilbert** [graphile/postgraphile#577]
I have a postgres column `created_at`, but postgraphql is auto-converting it to `createdAt`. Because this is a legacy application, I need the column to remain in the `created_at` format. Is there a way to tell postgraphql to leave the column names as-is?

**Comment by benjie** [comment]
Almost! With version 4 you will have a *lot* of control over how things are named if you so desire. You can implement your own inflector based on our standard inflector:

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/inflections.js

I've not yet got around to hooking the inflector up so that it's configurable from postgraphql - at the moment we only let you toggle between the two standard inflectors:

https://github.com/graphile/graphile-build/blob/master/packages/postgraphile-core/src/index.js#L81-L83

You can do it via `graphqlBuildOptions` but that's a temporary hack I'll be renaming before release.

**Comment by benjie** [comment]
You can track this issue I just created:

https://github.com/graphile/graphile-build/issues/62

**Comment by chadfurman** [comment]
@benjie this is closed now because of https://github.com/graphile/graphile-build/issues/62 correct?

**Comment by benjie** [comment]
I'm going to leave it open until there's documentation around it (I'm still treating it as alpha quality until then, and reserving the right to make small changes); but thanks for checking 👍

**Comment by benjie** [comment]
This is what counts for documentation currently:

https://github.com/postgraphql/postgraphql/pull/506#issuecomment-328831456

**Comment by benjie** [comment]
The above  doesn't work right now (because `makeAddInflectorsPlugin` only adds, not replaces, inflectors); but here's an example on how to replace inflectors:

https://www.graphile.org/postgraphile/plugin-gallery/#Inflector__PgShortenAllRowsInflectorPlugin

**Comment by tyrauber** [comment]
Note to future me: you need to pass true as the second option to makeAddInflectorsPlugin, otherwise you will receive an error `A naming conflict has occurred`.

The following works:
```
const { makeAddInflectorsPlugin } = require('graphile-utils');
const { formatInsideUnderscores } = require('graphile-build');
const snakeCaseAll = require("lodash/snakeCase");

module.exports = makeAddInflectorsPlugin({
  camelCase: formatInsideUnderscores(snakeCaseAll),
}, true);
```

**Comment by benjie** [comment]
Yes, override the column inflector.

**Comment by disarticulate** [comment]
for those interested, thats basically:

```
const { makeAddInflectorsPlugin } = require('graphile-utils')

module.exports = makeAddInflectorsPlugin(inflectors => {
  console.log(inflectors)
  return {
    column(attr) {
      return this._columnName(attr)
    }
  }
}, true)

```
