### ISSUE TITLE
Access  resources without token after enabled token based authorization

### ISSUE THREAD

**Issue by jamsheer-thottathil** [graphile/postgraphile#582]
I have enabled token based authorization in postgraphql by using  --secret and its working fine.
But if I miss the 'Authorization' header in the request it will work same as a none token based execution.
Is it expected?

**Comment by benjie** [comment]
It sounds like you might not have implemented any security in your database schema? Have a read of this:

https://www.graphile.org/postgraphile/security/

and this:

https://www.graphile.org/postgraphile/postgresql-schema-design/#authentication-and-authorization

**Comment by freiit** [comment]
`--secret` only specifies the key to the signature of the jwt. The token itself is not encrypted. You can create jwt token yourself for example with https://jwt.io. 
The postGraphQL-service must allow access to the database without token, otherwise you can't call the jwt creation functions. 
With roles and/or an account_id (or whatever) and row level security on db level you can restrict actions.

**Comment by hmaurer** [comment]
Should this be closed @benjie ? This is documented well on the website now.
