### ISSUE TITLE
Print the notice log within postgres stored procedures (plv8 as well) into postgraphql response log

### ISSUE THREAD

**Issue by pencilcheck** [graphile/postgraphile#607]
Is it possible to do that? it would be nice for debugging purposes.

Cheers

**Comment by benjie** [comment]
Yep; you just need to do `pgClient.on('notice', msg => ... )` after you grab a client from the pool.

PR welcome 👍

**Comment by pencilcheck** [comment]
You mean something like https://github.com/postgraphql/postgraphql/blob/0631012372512723774fd5dd66562b962e7c27c8/src/__tests__/utils/withPgClient.ts Then use the pgClient instance that you passed into the library to get the notice logs?

**Comment by benjie** [comment]
Here's where the SQL queries are intercepted for logging:

https://github.com/postgraphql/postgraphql/blob/1fa4310dae82d1a28636cb0fc6d4f8294729c5a2/src/postgraphql/withPostGraphQLContext.ts#L54-L57

You may want to add the `pgClient.on('notice', ...)` there - be sure to remove it again in the `finally` block:

https://github.com/postgraphql/postgraphql/blob/1fa4310dae82d1a28636cb0fc6d4f8294729c5a2/src/postgraphql/withPostGraphQLContext.ts#L81-L84

If you added a CLI flag to enable this logging I'd be happy to review the PR 👍

**Comment by arshadkazmi42** [comment]
@benjie I would like to work on this.
I have few questions.
 - What needs to be passed in the msg `pgClient.on('notice', msg => ... )`
 - What is the syntax to remove notice, which needs to be done finally block

**Comment by benjie** [comment]
Awesome, thanks @arshadkazmi42!

I think the best way of achieving this is in `withPostGraphileContext`. Add

```js
const debugPgNotice = createDebugger('postgraphile:postgres:notice');
```

Then here:

https://github.com/graphile/postgraphile/blob/ad6137abf93ee5543748c4dee7ec58d37ef9a8c9/src/postgraphile/withPostGraphileContext.ts#L99

Tweak to `(debugPg.enabled || debugPgError.enabled || debugPgNotice.enabled)`

Then here:

https://github.com/graphile/postgraphile/blob/ad6137abf93ee5543748c4dee7ec58d37ef9a8c9/src/postgraphile/withPostGraphileContext.ts#L344-L357

Wrap with `if (debugPg.enabled || debugPgError.enabled) {...}` (since notice doesn't require this override) and add above this the `pgClient.on('notice', ...)`

The notice should just log out the error via the new debugPgNotice. Please be sure to use the formatter to output the message via an additional argument rather than outputting it as the first argument (which is interpretted as a format string, hence risky to do this). https://www.npmjs.com/package/debug#formatters

If you do it this way, you won't need to clean up the notice.

Debug message could just be something like `debugNotice('NOTICE: %s', msg)` but if you can find out where the message originated (e.g. the PostgreSQL function) from the `msg` object (assuming it is an object...?) then that would be super helpful too, e.g. `debugNotice('NOTICE[%s]: %s', msg.origin, msg.text)`. You'll need to research that.

**Comment by arshadkazmi42** [comment]
@benjie Thank you for the detailed information.

I made the changes you suggested.
But cannot figure it out, what is the msg here?

`debugNotice('NOTICE: %s', msg) `

> Lines 344 to 357 in [ad6137a](/graphile/postgraphile/commit/ad6137abf93ee5543748c4dee7ec58d37ef9a8c9)
>  // tslint:disable-next-line only-arrow-functions 
>  pgClient.query = function(...args: Array<any>): any { 
>    // Debug just the query text. We don’t want to debug variables because 
>    // there may be passwords in there. 
>    debugPg(args[0] && args[0].text ? args[0].text : args[0]); 
>   
>    // tslint:disable-next-line no-invalid-this 
>    const promiseResult = pgClient[$$pgClientOrigQuery].apply(this, args); 
>   
>    // Report the error with our Postgres debugger. 
>    promiseResult.catch((error: any) => debugPgError(error)); 
>   
>    return promiseResult; 
>  }; 
> 
> Wrap with `if (debugPg.enabled || debugPgError.enabled) {...}` (since notice doesn't require this override) and add above this the `pgClient.on('notice', ...)`
> 

My code block looks something like this

<img width="594" alt="screen shot 2018-10-04 at 9 08 07 pm" src="https://user-images.githubusercontent.com/4654382/46485734-ebc39080-c819-11e8-83a5-630d9ae22d2a.png">

**Comment by benjie** [comment]
The `pgClient.on('notice')` line should be something like:

```js
pgClient.on('notice', (msg) => {
  const message = /* something */;
  debugNotice('NOTICE: %s', message)
});
```

You can put `console.dir(msg)` in the function and see what's output on notice and go from there, or you can read the node-postgres docs. I'm not sure exactly what it'll involve

**Comment by arshadkazmi42** [comment]
I found this on `node-postgres` docs, looks like I need to pass `msg`  to `debugNotice`

https://node-postgres.com/api/client#client-on-39-notice-39-notice-string-gt-void-gt-void

after that change does it needs any other update? Or I can create a PR?

**Comment by benjie** [comment]
Looks like that's it. Shame there's no extra metadata. Oh well 🤷‍♂️

**Comment by benjie** [comment]
(Please create PR)

**Comment by arshadkazmi42** [comment]
@benjie created PR
