### ISSUE TITLE
Exporting the data in GraphiQL interface

### ISSUE THREAD

**Issue by Tritpi** [graphile/postgraphile#659]
Can the data response got back in the GraphiQL interface be exported into some local file in postgraphql.

**Comment by benjie** [comment]
I’m not sure exactly what/why you’re asking... you can copy/paste it into a file, or you can write a very small script to run the GraphQL query against PostGraphQL and write the response to a file. The only file writing capabilities PostGraphQL has built in relate to exporting the schema.

https://www.graphile.org/postgraphile/usage-cli/

**Comment by Tritpi** [comment]
Is there an option to export the json response (i.e. the data retrieved after the query is run) got back in the GraphiQL interface to a local file. The purpose here is to compare the data retrieved in the GraphiQL 
 interface with the data in the database.

**Comment by benjie** [comment]
Easiest way is to just copy and paste the results into a file?

**Comment by chadfurman** [comment]
@Tritpi you can turn on the query-log in the DB, I think the introspection query is a single GraphQL statement which Postgraphile turns into a single select statement (I could be wrong on this).  

@benjie I think he wants to run the introspection query manually, though I'm not sure what this will prove.  I'm guessing he's trying to see why a table isn't being included in the auto-crud stuff, and I'd suggest it's because his list of included schemas does not include the one he's looking for -- I don't see any other reason he could want to see the introspection query from graphiql in terms of debugging...

**Comment by benjie** [comment]
PostGraphQL runs this SQL introspection query:

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/res/introspection-query.sql

and then uses that (and a hell of a lot of logic) to build the GraphQL schema in memory.

---

Any spec-compliant GraphQL schema can be introspected via the GraphQL introspection query which is available in the `graphql` module via

```js
import { introspectionQuery } from 'graphql';

//or: const { introspectionQuery } = require('graphql');
```

https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js#L18

Hope this helps.

**Comment by hmaurer** [comment]
Close @benjie ? The problem seems solved.
