### ISSUE TITLE
Package.json should use explicit versions

### ISSUE THREAD

**Issue by chadfurman** [graphile/postgraphile#702]
I'm submitting a ... 

* [X] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: Latest beta

Currently, package.json is using "atleast" syntax for dependencies.  Dependencies should be using explicit package versions.  For example ``` "pg-connection-string": "^0.1.3",``` relies on the package maintainer to follow semver correctly and not everyone does!  :)

Previously, being on an alpha version of the library (4.0.0-alpa.2.26),  a similar line caused breakage for me when rebuilding later:
``` "pg-sql2": "^1.0.0-alpha1.0",```  due to a dependency on a higher version of node which I am not willing to upgrade to...

**Comment by benjie** [comment]
Sorry about this; published pg-sql2@1.0.0-beta.8 which is identical to pg-sql2@1.0.0-beta.3 and supports Node v4 again. Will be releasing a pg-sql2@2.* that ups the minimum node version.

**Comment by benjie** [comment]
(I don't support using explicit version numbers in libraries in general unless the library has proven to not respect semver (or if it's a pre-release version such as alpha/beta/rc) because it results in far too much redundancy in node_modules and it also makes it a lot harder for users to fix security vulnerabilities as they can't do point-updates on dependencies.)
