### ISSUE TITLE
Adding a new column with alter table, restart postgraphile and in graphiql the create* method doesn't get updated with the new columns but it shows up in the return type

### ISSUE THREAD

**Issue by pencilcheck** [graphile/postgraphile#776]
I'm submitting a ... 

* [X] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:
`v4.0.0-rc.1`

Minimal SQL file that can be loaded into a clean database:

```sql
CREATE SCHEMA default_schema
  CREATE TABLE tracking_event (
    session_id          text NOT NULL,
    event_type          text NOT NULL,
    time                timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY (session_id, event_type, time)
  )
;

ALTER TABLE default_schema.tracking_event
ADD COLUMN user_id varchar(255);
```

Steps to reproduce:

Library
```
app.use(postgraphile(connectArgs, 'default_schema', {
  appendPlugins: [PostGraphileConnectionFilterPlugin],
  dynamicJson: true,
  enableCors: true,
  graphiql: true
}))
```

1. Setup schema
2. Run the server
3. Open graphiql to confirm that it works
4. Run the second SQL that adds the new column
5. Open graphiql and notice that it doesn't work

Current behavior:

In graphiql
```
Mutation.createTrackingEvent
```
will have the input that accepts
```
CreateTrackingEventInput {
  clientMutationId: String
  An arbitrary string value with no semantic meaning. Will be included in the payload verbatim. May be used to track mutations by the client.

  inputSessionId: String
  inputEventType: String
  inputTime: Datetime
}
```

Expected behavior:

The input should accept the newly created column `userId`

**Comment by pencilcheck** [comment]
I indeed restart the server multiple times (I believe the watch mode should be on by default) just to make sure that it was properly reloaded and I even removed `node_modules` and reinstall dependencies to make sure no cache was interfering but none of those works.

What I notice immediately is that in your graphiql, the input variables are different. In my version all of those has input* prefix.

As I mentioned before, the return type of the CreateTrackingEvent has the added field just not in the input type that the API requires.

I was really confused because this used to work all the time but somehow I just can't make this work for this instance of the current project and I really need to make this work.

**Comment by benjie** [comment]
> I believe the watch mode should be on by default

It's not, I do not advise using it in production (specifically because it makes changes to your database schema) so we don't enable it by default. `watchPg: true` is what you need, I think?

> how did you arrive to that page

I don't have my laptop handy right now so can't refer to the concrete terms, but from memory I clicked through something like:

- `mutation: Mutation` (click `Mutation`)
- `createTrackingEvent(input: CreateTrackingEventInput!)` (select `CreateTrackingEventInput`)
- `CreateTrackingEventInput: { clientMutationId, trackingEvent: TrackingEventInput }` (select `TrackingEventInput`)

`CreateTrackingEventInput` won't have the column on it directly - it probably only accepts the two fields `clientMutationId` and `trackingEvent`, the latter being an object input type with the fields you're looking for.

Perhaps you can upload a screenshot of what you see (like I did) and we can solve the issue?
