### ISSUE TITLE
Proposal -- Separate out postgraphile-cli from postgraphile (main)

### ISSUE THREAD

**Issue by sjmcdowall** [graphile/postgraphile#779]
I'm submitting a ... 

* [ ] bug report
* [ X ] feature request
* [ ] question 

PostGraphile version: 4.0 beta

This is just sort of an idea i've been pondering -- it seems to be that postgraphile-cli and the core library are really two different separations of concerns .. and as such .. maybe have two repo's ... one just for the CLI aspects (including the docker stuff, etc) and then the other for the pure postgraphile Middleware logic (that of course the CLI repo would have as a dependency).  

That way, if some tweaks to the CLI layer happens no need to repackage the postgraphile library and vice-versa (well sort of .. obviously any changes to postgraphile library you could probably want an updated CLI?) .. 

Anyway -- just seems a cleaner approach to me .. <shrug> 

Cheers!

**Comment by benjie** [comment]
I've considered this also; however the CLI is only a very small layer over the library - literally just this one file:

https://github.com/graphile/postgraphile/blob/master/src/postgraphile/cli.ts

Mostly it's responsible for converting CLI args into args that the library understands. In the end I decided that maintaining it as two separate modules would not confer sufficient benefit to justify splitting it up - any change to the library will require the CLI to update, and any update to the CLI is most likely because the library accepts new options. It wouldn't make non-CLI apps much thinner (a kB or two, nothing much) and it wouldn't make CLI apps any thinner (fatter actually as there'd be more overhead).

What I would like to do, however, is separate PostGraphile's GraphiQL app into a separate package. But that's a topic for a different issue!

Thanks for your input 🙏  I'm going to close this for now.
