### ISSUE TITLE
Option to remove query from mutation

### ISSUE THREAD

**Issue by degroote22** [graphile/postgraphile#802]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version: 4.0.0-rc.2

I'm working with schema stitching and I can't get the front schema to be fully typed because what it returns as query is different than what postgraphile return as query inside all mutations.
I get this is an awesome feature but I don't need it and it is making my life harder.
I guess it wouldn't hurt to make a setting that would allow us to turn this feature off.

I will look into it and submit a PR.

**Comment by degroote22** [comment]
No need for a PR.
This can be solved in userland.

```typescript
const { postgraphile } = require("postgraphile");
const buildPlugins = require("graphile-build");
const { defaultPlugins } = require("graphile-build-pg");

const defaultPluginsToChange = [
  buildPlugins.StandardTypesPlugin,
  buildPlugins.NodePlugin,
  buildPlugins.QueryPlugin,
  buildPlugins.MutationPlugin,
  buildPlugins.SubscriptionPlugin,
  buildPlugins.ClientMutationIdDescriptionPlugin
  // buildPlugins.MutationPayloadQueryPlugin,
];

const postgraphileSchemaOptions = {
  replaceAllPlugins: [...defaultPluginsToChange, ...defaultPlugins],
};
const pg = postgraphile(
  process.env.DATABASE_URL
);
```

**Comment by benjie** [comment]
Exactly - well spotted - just skip the plugin 👍

**Comment by benjie** [comment]
(And yes, there will be a lot more features for picking and choosing plugins in the future.)

**Comment by sjmcdowall** [comment]
This would be a wonderful GIST sort of article on how to do this until the "new and improved and well documented" plugin choosing happens.  :)

**Comment by benjie** [comment]
I'd recommend that instead of doing what you've done here; you should just filter the one you don't want from the array so that you still get the other graphile plugins we'll add over time. Not doing so may result in breakage as the larger plugins will likely be split up into smaller plugins over time.

```js
const { defaultPlugins: defaultGraphileBuildPlugins, MutationPayloadQueryPlugin } = require('graphile-build');
const defaultPluginsToChange = defaultGraphileBuildPlugins.filter(p => p !== MutationPayloadQueryPlugin);
```

Feel free to add a small section on this to the graphile docs:

https://www.graphile.org/postgraphile/extending/#graphql-schema-plugins

https://github.com/graphile/graphile.github.io/blob/develop/src/pages/postgraphile/extending.md
