### ISSUE TITLE
showErrorStack property does not perform as documented

### ISSUE THREAD

**Issue by cdaringe** [graphile/postgraphile#804]
* [x] bug report

PostGraphile version: 4.0.0-rc2

Current behavior:

- showErrorStack always returns an array when present, regardless if used as a flag or with `=json`

Expected behavior:

https://github.com/graphile/postgraphile/pull/794/files/74d5a2eb564fd7201128a35242c1b32b73fac8a6#r204086721

Steps to reproduce:

the below demonstrates setting `--show-error-stack` just a flag, an option with the `json` arg, and omitting entirely.

- docker run --rm -it -d -p 5432:5432 postgres:alpine
- psql -U postgres -h localhost
- run

```sql
CREATE or replace FUNCTION biff() RETURNS real AS $$
BEGIN
    RETURN 1 / 0;
END;
$$ LANGUAGE plpgsql stable;
```
- npx postgraphile -c postgres://postgres@localhost/postgres -s public `--show-error-stack`

in graphiql

```gql
{
  biff
}
```

==>

with `--show-error-stack`
```json
{
  "errors": [
      ...
      "stack": [
        "error: division by zero",
        "    at Connection.parseE (/Users/cdieringer/node/postgraphile/node_modules/pg/lib/connection.js:553:11)",
      ...
```

`--show-error-stack=json`

```js
{
  "errors": [
      ...
      "stack": [
        "error: division by zero",
        "    at Connection.parseE (/Users/cdieringer/node/postgraphile/node_modules/pg/lib/connection.js:553:11)",
```

without `--show-error-stack`

```js
// this shows as expected. no stack
{
  "errors": [
    {
      ...
```

**Comment by benjie** [comment]
This does not occur for me:

```json
{
  "errors": [
    {
      "message": "division by zero",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "biff"
      ],
      "stack": "error: division by zero\n    at Connection.parseE (/Users/benjiegillam/Dev/CLEAN/node_modules/pg/lib/connection.js:553:11)\n    at Connection.parseMessage (/Users/benjiegillam/Dev/CLEAN/node_modules/pg/lib/connection.js:378:19)\n    at Socket.<anonymous> (/Users/benjiegillam/Dev/CLEAN/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:180:13)\n    at addChunk (_stream_readable.js:274:12)\n    at readableAddChunk (_stream_readable.js:261:11)\n    at Socket.Readable.push (_stream_readable.js:218:10)\n    at TCP.onread (net.js:581:20)"
    }
  ],
  "data": {
    "biff": null
  }
}
```

Command: `yarn postgraphile --watch -c postgres://localhost/pggql_test --show-error-stack`

Further it seems impossible from the code:

1. assigned a boolean true here if CLI is set (note that the argument parser does not support the `=json`; it simply ignores it), or null otherwise: https://github.com/graphile/postgraphile/blob/5f48a083a5041c67ffef1acc804c3c8056ac3126/src/postgraphile/cli.ts#L102

2. dereferenced here (still boolean): https://github.com/graphile/postgraphile/blob/5f48a083a5041c67ffef1acc804c3c8056ac3126/src/postgraphile/cli.ts#L229

3. passed through to options here (still boolean): https://github.com/graphile/postgraphile/blob/5f48a083a5041c67ffef1acc804c3c8056ac3126/src/postgraphile/cli.ts#L365

4. passed to the middleware here (still boolean): https://github.com/graphile/postgraphile/blob/5f48a083a5041c67ffef1acc804c3c8056ac3126/src/postgraphile/cli.ts#L450

5. finally used here: https://github.com/graphile/postgraphile/blob/bb851da999e0c546e827fe2f4626172f1fce0a4e/src/postgraphile/http/createPostGraphileHttpRequestHandler.js#L186-L190

Only if `options.showErrorStack === 'json'` is the stack split, and clearly that cannot be the case unless .postgraphilerc is getting involved.

---

I wonder if you have `showErrorStack: 'json'` in a .postgraphilerc file, or if you're using a non-released version of postgraphile?

**Comment by benjie** [comment]
If you manage to reproduce this with a clean install of the latest code, please re-open.
