### ISSUE TITLE
Add JWT claims to GraphQL context (so plugins can access them)

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#824]
Temporary workaround: use `additionalGraphQLContextFromRequest` with the library version and parse the JWT again yourself. Sorry.

**Comment by sjmcdowall** [comment]
Do you have a little example code snippet for this?

The reason I ask is that we are creating some mutations -- some of which access external REST api's and we need to pass our Authorization Header with our Bearer token downstream to the rest API's and I was wondering how to access the req.headers within our mutation logic?

**Comment by benjie** [comment]
Add to your PostGraphile options something like:

```
additionalGraphQLContextFromRequest: req => ({
  headers: req.headers
})
```

JWT parsing is left as an exercise to the reader.

**Comment by sjmcdowall** [comment]
We actually parse the JWT and add it to the Koa Context before postgraphile is called, so our JWT should be in the context (ctx) ..but we're not seeing it?  I am pretty sure the access is via "ctx.state.jwt" .. 

 Is that routine above ONLY for the request object off the context or can we access any item that's on the context (and the context is the "context" that is passed in from Koa/Express, right? Postgraphile doesn't do anything funky with the context/ctx?  So anything added BEFORE postgraphile is invoked should be available?

I am asking because Scott says he isn't seeing the objects I added to ctx in his plugin for the mutation?? 
I haven't investigated this in any detail --

**Comment by sjmcdowall** [comment]
Exctly what I came up with in a dream last night!  :) 

THanks!

**Comment by benjie** [comment]
Solved by https://github.com/graphile/postgraphile/pull/829

**Comment by alexisrolland** [comment]
@sjmcdowall  would you mind providing a more detailed example where you added `additionalGraphQLContextFromRequest` in your code so that your plugin could access it please?

I'm trying to achieve something similar and I don't understand which code snippet should go where.
Thanks

**Comment by rrmckinley** [comment]
@alexisrolland here's and example
```javascript
// Add the follow function to `postgraphileOptions: {..., additionalGraphQLContextFromRequest, ...}`
export const additionalGraphQLContextFromRequest = (req, res) => {
  return {
    getCookie: cookieName => req.cookies[cookieName],
    setCookie: (cookieName, value, options) => res.cookie(cookieName, value, options)
  };
};
```

**Comment by alexisrolland** [comment]
Thanks @rrmckinley it helped!

**Comment by rrmckinley** [comment]
@alexisrolland Glad to hear it. I edited it a few times before you replied, but I think that's everything you need now.
