### ISSUE TITLE
Access different db strings based on graphql query params

### ISSUE THREAD

**Issue by thewillhuang** [graphile/postgraphile#898]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

for successfully being able to access different database shards based on some pre-defined graphql query parameters

**Comment by benjie** [comment]
Could you give examples of how you want this to work?

**Comment by thewillhuang** [comment]
say i input companyId, it maps through redis to get the shard to talk to another psql db

**Comment by benjie** [comment]
Could you give full examples including the GraphQL queries you want to run and how you see them resolving / connecting to various databases? What you're asking at the moment seems quite ambiguous so please make it more concrete with thorough examples.

**Comment by benjie** [comment]
Are the database schemas 100% identical?

**Comment by thewillhuang** [comment]
yep!

**Comment by benjie** [comment]
Interesting. So... Theoretically you could [wrap the resolver](https://www.graphile.org/postgraphile/extending-raw/#wrapping-an-existing-resolver) and pass through a different `pgClient` on the `context` argument. You'd need to set up the new pgClient with all the relevant settings that were set on the default one, but that's basically what you'd need to do. It'd only work for the single query tree though (e.g. it might not work for mutations). It's a risky approach (might break in future, and the break would be exposing data from the wrong DB which is definitely not what you want!), but it could work.

There's not a reliable way of doing this in PostGraphile v4 directly, because everything uses the `pgClient` on context. Instead I think what I would do is build a new GraphQL schema with a root level field to switch between the companies, and then have that call out to different postgraphile instances depending on which company was selected.

**Comment by benjie** [comment]
I'm going to close this because it's beyond the scope of PostGraphile at the moment (you might want to revisit in v5); but feel free to keep discussing below 👍

**Comment by thewillhuang** [comment]
roger, thank you!
