### ISSUE TITLE
consider using "set search_path from current" in examples/forum

### ISSUE THREAD

**Issue by srghma** [graphile/postgraphile#927]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

Hi, @benjie , I found you are using `set search_path from current` on almost all functions here

https://github.com/graphile/examples/blob/8751308ebd3a7a1350158e1eec164d3330d785d6/db/400_users.sql#L3

Why you do this and why not to do this in examples/forum/schema.sql because it's the first place where newbies go to? tnx

**Comment by srghma** [comment]
Let me guess

You do this because the default postgres search_path is `"$user",public` (https://www.endpoint.com/blog/2012/11/15/postgresql-searchpath-behaviour)

thus, the first searched schema depends on the content of `session_user`

**Comment by benjie** [comment]
The forum example is very old; the plan is to remove it once bootstrap-react-apollo is complete. I build PostGraphile schemas in quite a different way to how the forum example works.

Adding `set search_path from current` is an important clause if you think a user might be able to get direct access to your database. The reason is that they could change the search path to one that includes tables, functions or operators that they control and then call a `SECURITY DEFINER` function in the main schema and have it call their tables/functions instead of its ones. This can be used for privilege escalation.

Of course if you're certain an attacker can never connect directly to your database then this is not a concern; but I like to play it safe.

**Comment by benjie** [comment]
By the way, if you want to raise a PR that adds that to all the functions, I'd merge it 👍

The example schema is also now located on the website: https://www.graphile.org/postgraphile/postgresql-schema-design/
