### ISSUE TITLE
invalid tstzrange value formatting

### ISSUE THREAD

**Issue by mathroc** [graphile/postgraphile#941]
when getting the value of the lower bound of a tstzrange, I'm getting something like this : `"2018-12-17 09:48:12.69812+00"` instead of `2018-12-17T09:48:12.69812+00`

notice the extra quotes and the missing `T` between the date and time parts

I looked at the PgTypesPlugin but couldn't figure out what would be the way to solve that yet

ps: I did not try but I suspect there's the same problem with `tsrange`

**Comment by benjie** [comment]
Ahhhh very interesting. So this is because we rely on the `to_json` of timestamps putting them into ISO format within the DB. When we have a range we just get the range back (unprocessed), which we then parse and feed through the JS processing. In the case of dates, JS processing doesn't do anything _because_ the database already handled it. Except it didn't in this case... Hence the issue.

https://github.com/graphile/graphile-engine/blob/e5b1ba93ce550ba51da5e11cd644e3efdfc93cbd/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L669-L687

**Comment by benjie** [comment]
Just processing the date in JS is risky because it depends on the timezone of the server/connection. Our best bet might be to explicitly set the timezone to UTC when we create a PostgreSQL connection, pull the date through, then process it in JS. (And hope that the user doesn't want to/need to override the timezone in pgSettings.) We've managed to avoid having to do these client settings so far.

I shall give this some thought. Ideas welcome.

**Comment by sjmcdowall** [comment]
Isn't there some setting at the DB server level to the "default timezone" ?  I.e. doesn't one set the timezone (or can) at the server level?  Maybe the connection should set the TZ to whatever the server is at ?  If I am totally wrong -- then I think UTC is the best choice because these days it's certainly easy enough to switch to any other TZ desired ...

**Comment by mathroc** [comment]
could we build the json in the query? with something like:

```sql
select jsonb_build_object(
        'lower', jsonb_build_object('value', lower(range), 'inclusive', lower_inc(range)),
        'upper', jsonb_build_object('value', upper(range), 'inclusive', upper_inc(range))
    )
```

**Comment by benjie** [comment]
Yes, we absolutely could do that. Smart 👍

**Comment by benjie** [comment]
@mathroc If you're interested in taking this on, you should be able to do this in a standalone plugin (though it should definitely be merged into core!); e.g. this is part of a plugin that adds support for the hstore type:

https://github.com/graphile/graphile-engine/blob/7c712a9704642221438d93f6716cd04332d54ac3/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L1012-L1022


The main things here are you're registering the output and input types by id; the Range types are constructed like this:

https://github.com/graphile/graphile-engine/blob/7c712a9704642221438d93f6716cd04332d54ac3/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L593-L660

You need to figure out the array type for timestamptz, a bit like this:

https://github.com/graphile/graphile-engine/blob/7c712a9704642221438d93f6716cd04332d54ac3/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L997-L999

but using the array-related things, and the fact you know that timestamptz is always OID `1184`:

https://github.com/graphile/graphile-engine/blob/7c712a9704642221438d93f6716cd04332d54ac3/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L432

Then you need to implement the `pg2GqlMapper` for the relevant type, this is responsible for converting PostgreSQL results to GraphQL-compatible results, and for converting GraphQL inputs to PostgreSQL values

Like this:

https://github.com/graphile/graphile-engine/blob/7c712a9704642221438d93f6716cd04332d54ac3/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L663-L703

You can use `pgTweakFragmentForTypeAndModifier` to tell PostgreSQL to do a particular operation when fetching a field of a particular type. Internally we only use this for a few things:

https://github.com/graphile/graphile-engine/blob/7c712a9704642221438d93f6716cd04332d54ac3/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L277-L286

But we also use it for more complex stuff in the PostGIS plugin:

https://github.com/benjie/graphile-build-postgis/blob/0cf28f76b5a41dbd345738bd968c886c65c832fa/plugins/GeographyPointPlugin.js#L200-L219

(Namely to convert to GeoJSON.)

Also, we'll need tests for this (both read and write).

Of course feel free to ask me questions over Discord; we're in similar timezones so it should be good 👍

**Comment by benjie** [comment]
As evidenced by the commits above, @mathroc is taking this on via: https://github.com/graphile/graphile-engine/pull/371

🙏 Thanks @mathroc!

**Comment by benjie** [comment]
Fixed in the above PR

**Comment by benjie** [comment]
postgraphile@next (4.3.1) is now out 👍
