### ISSUE TITLE
Why do the docs recommend a custom schema instead of just the public schema?

### ISSUE THREAD

**Issue by adrianwe** [graphile/postgraphile#988]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

To take the [Postgres schema design guide](https://www.graphile.org/postgraphile/postgresql-schema-design/#grants) as an example, what would I have to change in order to just use the public schema?

- I would obviously not have to grant "usage" to the public schema as all roles already have that by default.
- Would I have to revoke "create" though (which is also granted to every role by default) or is that unnecessary because users can only access the DB via Postgraphile and this does not expose create functionalities?
- I am wondering if the PUBLIC role, so all created roles as well, already have select and modification privileges to the created tables (and execute to functions) within the public schema by default? Because then I would have to revoke that somehow before re-applying the more fine-grained grants from the tutorial.

But even though I'm confused atm, I think the latter isn't the case which leads me to the question: Why not just use the public schema for non-private tables? The tutorial creates a "forum_example" schema and the [namespace docs](https://www.graphile.org/postgraphile/namespaces/) recommend calling it "app_public". However, I do not understand the benefit of doing that and it is not explained there. I feel like it just adds verbosity, but I don't see the benefit. I would appreciate if someone could shed some light on this. :-)

Thank you!

**Comment by benjie** [comment]
You can absolutely use the public schema; the main reasons that we advise using a custom schema is a) because it makes it very clear when you separate what will be exposed through GraphQL and what will not, and b) because extensions are installed into the public schema by default, so it gets quite polluted (but we automatically filter extension functionality now, so this is less of an issue than it used to be).

If you want to use the `public` schema, the easiest way is to fix its permissions to your preferences and use `--no-ignore-rbac` - that way we will only expose things that you explicitly `GRANT` privileges to. (You have to connect to PostgreSQL using your unprivileged role for this to work because the superuser can access everything, this will only work with `--watch` if you've already installed the watch fixtures which you can do by running `postgraphile --watch -c my_db` using databasesuperuser privileges.)

**Comment by adrianwe** [comment]
Thanks for your reply!

I have experimented a bit more in the meantime and I have learned that all my three assumptions were correct. So, with the third point being the most critical one, I have learned that the only grant that is already there for the `public` schema is `usage`. Whereas when the superuser creates tables in the `public` schema, you still have to grant select to every other user or he will not be able to access the tables.

This also is reflected in how the tables (and functions) are exposed to the GraphQL API using the `no-ignore-rbac` option. If I don't grant anything to a table to any of the roles that grant to the postgraphile role, then it will not show up in the API. This also works in a fine-grained way, for example exposing update mutations, but not insert mutations, if this is how the grants are specified. Using the `no-ignore-rbac` option has no security implications whatsoever though - when not using it the exposed functionality would still not work under the hood due to permissions (this is what I was mostly worried about). So, I'm guessing you should probably use that option no matter what, even if you don't want to use the `public` schema, just to keep your API organized.

**Comment by benjie** [comment]
Correct; noIgnoreRBAC will be default in v5. It’s only a flag right now for backwards compatibility.
